import { Product, CategoryKey } from './types';

/**
 * Delta Stars Sovereign Data Engine v102.0
 * قاعدة البيانات الشاملة والمعالجة (235 صنفاً فريداً)
 */

const fixDriveLink = (idOrUrl: string) => {
    if (!idOrUrl) return "https://images.unsplash.com/photo-1610348725531-843dff563e2c?q=80&w=500&auto=format&fit=crop";
    
    if (idOrUrl.startsWith('http')) return idOrUrl;

    let cleanId = idOrUrl;
    if (idOrUrl.includes('id=')) {
        const parts = idOrUrl.split('id=');
        cleanId = parts[parts.length - 1];
    } else if (idOrUrl.includes('/d/')) {
        const parts = idOrUrl.split('/d/');
        cleanId = parts[1].split('/')[0];
    }

    cleanId = cleanId.split('/view')[0].split('?')[0].split('&')[0];
    
    return `https://lh3.googleusercontent.com/d/${cleanId}`;
};

const mapUnitArToEn = (unitAr: string): string => {
    if (unitAr.includes('كيلو')) return 'kg';
    if (unitAr.includes('حبة')) return 'pc';
    if (unitAr.includes('عبوة')) return 'PK';
    if (unitAr.includes('كرتون')) return 'Ctn';
    if (unitAr.includes('طبق')) return 'Box';
    if (unitAr.includes('سلة')) return 'Basket';
    return 'unit';
};

const mapCategory = (catAr: string, nameAr: string): CategoryKey => {
  const name = nameAr.toLowerCase();
  const cat = catAr.toLowerCase();

  // Priority 1: Handle the mixed "Qassim, Dates & Others" category specifically
  if (cat.includes('القصيم') || cat.includes('تمور') || cat.includes('منوعة')) {
      // Check for Dates first within this category
      if (name.includes('تمر') || name.includes('سكري') || name.includes('مجدول') || name.includes('صقعي') || 
          name.includes('مبروم') || name.includes('صفاوي') || name.includes('عنبر') || name.includes('عجوة') || 
          name.includes('رطب') || name.includes('خلاص')) {
          return 'dates';
      }
      // Check for Packages/Baskets
      if (name.includes('سلة') || name.includes('صندوق') || name.includes('بيض') || name.includes('عبوة') || name.includes('مغلف')) {
          return 'packages';
      }
      // Check for Flowers
      if (name.includes('زهور') || name.includes('ورد')) return 'flowers';
      // Check for Fruits that might be here
      if (name.includes('توت') || name.includes('جوز الهند') || name.includes('قصب سكر') || name.includes('أناناس')) return 'fruits';
      // Check for Mushrooms
      if (name.includes('فطر')) return 'seasonal';
      
      // Default for this mixed category is Qassim
      return 'qassim';
  }

  // Priority 2: Standard Category Mapping
  if (cat.includes('تمور')) return 'dates';
  if (cat.includes('الورقيات') || cat.includes('أعشاب')) return 'herbs';
  if (cat.includes('الفواكه')) return 'fruits';
  if (cat.includes('المستوردة والخاصة')) return 'seasonal';
  if (cat.includes('الأساسية والمحلية')) return 'vegetables';
  if (cat.includes('مكسرات')) return 'nuts';
  if (cat.includes('زهور')) return 'flowers';

  // Fallback
  return 'vegetables';
};

// البيانات الخام لـ 235 منتج كما تم توفيرها بدقة
const rawJsonData = [
  { "id": 1, "category": "الخضروات الأساسية والمحلية", "name_ar": "بطاطس محلي", "name_en": "Potato Local", "description": "بطاطس وطنية طازجة من أجود الأصناف المحلية، تتميز بحجمها المتوسط وقشرتها الرقيقة ولونها الذهبي.", "features": "مصدر غني بالكربوهيدرات والفيتامينات، قوامها مثالي للقلي والسلق والطبخ", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "1xb0Noh8tIEK83VAi8yv280Si8LqIbX7K" },
  { "id": 2, "category": "الخضروات الأساسية والمحلية", "name_ar": "بصل أحمر محلي", "name_en": "Red Onion Local", "description": "بصل أحمر طازج من المزارع الوطنية، يتميز بلونه الأرجواني الجذاب ونكهته القوية والحادة قليلاً.", "features": "غني بمضادات الأكسدة، مثالي للسلطات الطازجة والطبخ والشوي", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "1jEUeunFAQE_dB038Dvgpsj1at7hm0DpE" },
  { "id": 3, "category": "الخضروات الأساسية والمحلية", "name_ar": "طماطم مدور محلي", "name_en": "Tomato Round Local", "description": "طماطم مدورة وطنية ذات لون أحمر زاهي، تتميز بعصارتها الغنية وطعمها الحلو المميز.", "features": "مصدر ممتاز لفيتامين C ومضادات الأكسدة، مثالية للسلطات والصلصات والطبخ", "origin": "إنتاج وطني (محلي)", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "11b289syxUXd-3Zgdl1kb5SxDWk2EQebM" },
  { "id": 4, "category": "الخضروات الأساسية والمحلية", "name_ar": "خيار محلي", "name_en": "Cucumber Local", "description": "خيار وطني طازج ومقرمش، يتميز بقشرته الخضراء الداكنة ولبه الأبيض المنعش.", "features": "منعش ومرطب، منخفض السعرات الحرارية، مثالي للسلطات والمقبلات", "origin": "إنتاج وطني (محلي)", "price": 4.5, "price_unit": "ريال للكيلو", "image_url": "1X3PIUywJ5sfMG25XClp-IFq5zNxRig9c" },
  { "id": 5, "category": "الخضروات الأساسية والمحلية", "name_ar": "جزر محلي", "name_en": "Carrot Local", "description": "جزر وطني طازج بلون برتقالي زاهي، مقرمش وحلو المذاق. يتميز بحجمه المتوسط وجودته العالية.", "features": "غني بفيتامين A والبيتا كاروتين، مثالي للأكل الطازج والسلطات والعصائر", "origin": "إنتاج وطني (محلي)", "price": 4.5, "price_unit": "ريال للكيلو", "image_url": "1zqTZL1IhHr_pHolwgtDrfWeJ6YBYkXmC" },
  { "id": 6, "category": "الخضروات الأساسية والمحلية", "name_ar": "كوسة محلي", "name_en": "Zucchini Local", "description": "كوسة وطنية طازجة ذات لون أخضر فاتح، تتميز بملمسها الناعم وطعمها اللذيذ.", "features": "منخفضة السعرات الحرارية، غنية بالألياف، مثالية للحشي والسلق والقلي", "origin": "إنتاج وطني (محلي)", "price": 6.0, "price_unit": "ريال للكيلو", "image_url": "1HZsTzb_wyF6xnbvTICXUHWnmDGrNEm7Y" },
  { "id": 7, "category": "الخضروات الأساسية والمحلية", "name_ar": "باذنجان أسود مدور", "name_en": "Eggplant Round", "description": "باذنجان أسود مدري وطني، ذو شكل كروي مميز ولون أرجواني داكن لامع.", "features": "غني بالألياف ومضادات الأكسدة، مثالي للشوي والحشي وصنع المتبل", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "17vvpbMoeuIdE2I1ggaTgxFi8I4LEJ2oZ" },
  { "id": 8, "category": "الخضروات الأساسية والمحلية", "name_ar": "رومي أخضر محلي", "name_en": "Green Capsicum Local", "description": "فلفل رومي أخضر وطني، كبير الحجم وذو جدار سميك، يتميز بنكهته المنعشة والمقرمشة.", "features": "غني بفيتامين C، مثالي للحشو والسلطات والشوي", "origin": "إنتاج وطني (محلي)", "price": 6.0, "price_unit": "ريال للكيلو", "image_url": "1MUje2wJ-2ZcntP9r33Ts1WNU5U3YM8QK" },
  { "id": 9, "category": "الخضروات الأساسية والمحلية", "name_ar": "فلفل حار أخضر", "name_en": "Green Chili", "description": "فلفل حار أخضر طازج، يتميز بحرارته المتوسطة ونكهته المميزة.", "features": "غني بالفيتامينات، مثالي لإضافة نكهة حارة للطعام", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "1zAUCUhgZQjn0DIfeLfeYOfVTqkmCfII8" },
  { "id": 10, "category": "الخضروات الأساسية والمحلية", "name_ar": "ثوم محلي", "name_en": "Garlic Local", "description": "ثوم وطني طازج، ذو فصوص كبيرة ورائحة نفاذة، يتميز بنكهته القوية.", "features": "مضاد طبيعي للبكتيريا، غني بمضادات الأكسدة، أساسي في جميع الأطباق", "origin": "إنتاج وطني (محلي)", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "1R7opaVOiXqtejq4fmCVXjTD-r69HZJwP" },
  { "id": 11, "category": "الخضروات الأساسية والمحلية", "name_ar": "زهرة (قرنبيط)", "name_en": "Cauliflower", "description": "قرنبيط طازج أبيض ناصع، برؤوس متماسكة وأوراق خضراء طرية.", "features": "غني بفيتامين C والألياف، منخفض الكربوهيدرات، مثالي للشوي والسلق", "origin": "إنتاج وطني (محلي)", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "1vfE6cpExYTNUDX8I4fAQCgIb4WkDHRRT" },
  { "id": 12, "category": "الخضروات الأساسية والمحلية", "name_ar": "فاصوليا خضراء", "name_en": "Green Beans", "description": "فاصوليا خضراء طازجة ومقرمشة، ذات لون أخضر زاهي وحجم موحد.", "features": "غنية بالألياف والفيتامينات، مثالية للسلق والقلي والطبخ", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "1yVylYJh5SJ2Yux0tfSWANdvQ_V5QkpMc" },
  { "id": 13, "category": "الخضروات الأساسية والمحلية", "name_ar": "بامية محلي", "name_en": "Okra Local", "description": "بامية وطنية طازجة، صغيرة الحجم وطرية، ذات لون أخضر فاتح.", "features": "غنية بالألياف والفيتامينات، مثالية لتحضير اليخنات والطبخات التقليدية", "origin": "إنتاج وطني (محلي)", "price": 15.0, "price_unit": "ريال للكيلو", "image_url": "1hEvPts2YvZ4w-5SpZME6VGTMCWd9aUqR" },
  { "id": 14, "category": "الخضروات الأساسية والمحلية", "name_ar": "فطر بوتون أبيض", "name_en": "Button Mushroom White", "description": "فطر بوتون أبيض طازج، صغير الحجم وذو قوام متماسك.", "features": "منخفض السعرات الحرارية، غني بالبروتين والفيتامينات، مثالي للسلطات", "origin": "مستورد", "price": 23.0, "price_unit": "ريال للكيلو", "image_url": "1Poe99MM_d7gGlITeHzPDLz0Dg-YEPpX6" },
  { "id": 15, "category": "الخضروات الأساسية والمحلية", "name_ar": "أفوكادو كينيا", "name_en": "Avocado Kenya", "description": "أفوكادو كيني طازج، ذو قشرة خضراء داكنة، يتميز بقوامه الكريمي ونكهته الغنية.", "features": "غني بالدهون الصحية والفيتامينات، مثالي للسلطات والوجبات الصحية", "origin": "كينيا", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "11S3ki1pSUYsk3Wai4Er0vMpbG4x_Xp0K" },
  { "id": 16, "category": "الخضروات الأساسية والمحلية", "name_ar": "زنجبيل", "name_en": "Ginger", "description": "زنجبيل طازج بجذور سميكة ورائحة نفاذة، يتميز بنكهته الحارة المنعشة.", "features": "مضاد طبيعي للالتهابات، يعزز المناعة، مثالي للشاي والطبخ", "origin": "مستورد", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "1X_AaiaO8ChiELWDcwNHeEaEfrxIFz9lU" },
  { "id": 17, "category": "الخضروات الأساسية والمحلية", "name_ar": "لفت محلي", "name_en": "Turnip Local", "description": "لفت وطني طازج أبيض ناصع، ذو شكل كروي وقشرة ناعمة.", "features": "غني بفيتامين C والألياف، مثالي للتخليل والسلق والطبخ", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "1zgXc0Eart7zc06IH91fuX9y1BL9XV694" },
  { "id": 18, "category": "الخضروات الأساسية والمحلية", "name_ar": "بنجر محلي", "name_en": "Beetroot Local", "description": "بنجر وطني طازج بلون أحمر غامق، بحجم متوسط وقشرة ناعمة.", "features": "غني بالحديد والفولات، مثالي للسلطات والعصائر والطبخ", "origin": "إنتاج وطني (محلي)", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "1ywav9hEifTHYM6B1QZru2MVlxbg41sK_" },
  { "id": 19, "category": "الخضروات الأساسية والمحلية", "name_ar": "قرع عسلي", "name_en": "Pumpkin", "description": "قرع عسلي طازج بلون برتقالي زاهي، يتميز بحجمه المتوسط وقوامه الصلب.", "features": "غني بفيتامين A والألياف، مثالي للحساء والحلويات والطبخ", "origin": "إنتاج وطني (محلي)", "price": 5.5, "price_unit": "ريال للكيلو", "image_url": "1VH-BB0iSLxFzUUFUFe9cieuccia2NR6a" },
  { "id": 20, "category": "الخضروات الأساسية والمحلية", "name_ar": "باذنجان طويل", "name_en": "Eggplant Long", "description": "باذنجان طويل وطني بلون أرجواني غامق، يتميز بشكله المستدق وقوامه المتماسك.", "features": "قليل البذور، مثالي للشوي والقلي والحشي، يمتص النكهات بشكل رائع", "origin": "إنتاج وطني (محلي)", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "1lkXwO5bK4WILRT0LAxTczLHDlDe_xeKX" },
  { "id": 21, "category": "الخضروات الأساسية والمحلية", "name_ar": "باذنجان ابيض", "name_en": "Eggplant White", "description": "باذنجان أبيض نادر وفريد، بلون أبيض كريمي وقشرة ناعمة.", "features": "قوام كريمي، أقل مرة من الباذنجان العادي، مثالي للشوي والتحميص", "origin": "إنتاج وطني (محلي)", "price": 4.0, "price_unit": "ريال للكيلو", "image_url": "1uugZnjz-BbXpA_4wjvObFDlGOuWsSQup" },
  { "id": 22, "category": "الخضروات الأساسية والمحلية", "name_ar": "رومي احمر محلي", "name_en": "Red Capsicum Local", "description": "فلفل رومي أحمر وطني، يتميز بلونه الأحمر الزاهي ونكهته الحلوة المميزة.", "features": "أغنى بالفيتامينات من الأخضر، غني بفيتامين C، مثالي للسلطات", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "1wAnXeLCYIiNdXZmxfw6hcYp8ehgGO7tn" },
  { "id": 23, "category": "الخضروات الأساسية والمحلية", "name_ar": "رومي اصفر محلي", "name_en": "Yellow Capsicum Local", "description": "فلفل رومي أصفر وطني، بلون مشمس جذاب ونكهة حلوة وفاكهية.", "features": "غني بمضادات الأكسدة، مثالي لإضفاء لون ونكهة مميزة للأطباق", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "12_4sl3KxQwDQKK9xaHHoF-UTOWQY4zsp" },
  { "id": 24, "category": "الخضروات الأساسية والمحلية", "name_ar": "بامية صغير محلي", "name_en": "Small Okra Local", "description": "بامية وطنية صغيرة جداً وطرية، تعتبر من أجود أنواع البامية.", "features": "قوام ناعم ولذيذ، مثالية لليخنات والطبخات التقليدية الفاخرة", "origin": "إنتاج وطني (محلي)", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "12PjGonYbLI6BIl_cXoOqA9gotzIHVte2" },
  { "id": 25, "category": "الخضروات الأساسية والمحلية", "name_ar": "فلفل حار احمر", "name_en": "Red Chili", "description": "فلفل حار أحمر طازج، يتميز بلونه الأحمر الزاهي وحرارته المتوسطة إلى عالية.", "features": "غني بفيتامين C، مثالي للصلصات الحارة والطبخ، لون جذاب", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "1o4qsHBlEu5kZQ4Tm32Ecxk6g_RflbM8x" },
  { "id": 26, "category": "الخضروات الأساسية والمحلية", "name_ar": "ذرة (كوز)", "name_en": "Corn Cob", "description": "ذرة طازجة على الكوز، حباتها صفراء ذهبية وممتلئة، تتميز بحلاوتها الطبيعية.", "features": "غنية بالألياف والفيتامينات، مثالية للشوي والسلق كوجبة خفيفة", "origin": "إنتاج وطني (محلي)", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "1y5M3BGlPN6C_oYjYXRofC_9iKfl8fcTE" },
  { "id": 27, "category": "الخضروات الأساسية والمحلية", "name_ar": "قلقاس", "name_en": "Taro", "description": "قلقاس طازج بدرنات بنية اللون، يتميز بقوامه النشوي وطعمه المميز عند الطهي.", "features": "غني بالكربوهيدرات والألياف، مثالي للطبخ والسلق والقلي", "origin": "مستورد", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "1MrL36LfeWg5vgwLh59agQ5jC4dgDon0p" },
  { "id": 28, "category": "الخضروات الأساسية والمحلية", "name_ar": "بركلي محلي", "name_en": "Broccoli Local", "description": "بروكلي وطني طازج برؤوس خضراء مدمجة، يتميز بقوامه المقرمش ونكهته اللذيذة.", "features": "غني بفيتامين C و K ومضادات الأكسدة، مثالي للسلق والتبخير", "origin": "إنتاج وطني (محلي)", "price": 16.0, "price_unit": "ريال للكيلو", "image_url": "1mwLuQ-VVD4TAVIubHYcuvgFblWUWor2W" },
  { "id": 29, "category": "الخضروات الأساسية والمحلية", "name_ar": "ملفوف ابيض محلي", "name_en": "White Cabbage Local", "description": "ملفوف أبيض وطني طازج، برأس متماسك وأوراق مقرمشة.", "features": "غني بفيتامين C والألياف، مثالي للسلطات والمخللات والطبخ", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "1AUdC50i87tO4oK-sVBBHxpF7b-fhRikU" },
  { "id": 30, "category": "الخضروات الأساسية والمحلية", "name_ar": "ملفوف احمر محلي", "name_en": "Red Cabbage Local", "description": "ملفوف أحمر وطني بلون أرجواني جذاب، أوراقه مقرمشة ولذيذة.", "features": "غني بمضادات الأكسدة، مثالي للسلطات الملونة والمخللات", "origin": "إنتاج وطني (محلي)", "price": 4.5, "price_unit": "ريال للكيلو", "image_url": "1TYQIyMHSux6oNJa3em5fbsJuTjKs7yBZ" },
  { "id": 31, "category": "الخضروات الأساسية والمحلية", "name_ar": "آرتيشوك طازج", "name_en": "Fresh Artichoke", "description": "آرتيشوك طازج، برؤوس خضراء كبيرة، يتميز بطعمه الفريد وقوامه اللذيذ.", "features": "غني بالألياف ومضادات الأكسدة، مثالي للشوي والسلق", "origin": "مستورد", "price": 33.0, "price_unit": "ريال للكيلو", "image_url": "1PM-aMGPe3eq_R1Vu8dbvnCbpoYm_btBF" },
  { "id": 32, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون بيبي", "name_en": "Baby Asparagus", "description": "هليون بيبي طازج، براعم رفيعة وطرية، ذات نكهة دقيقة وحساسة.", "features": "غني بالفيتامينات، سريع الطهي، مثالي للقلي السريع أو التبخير", "origin": "مستورد", "price": 9.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "1KITXChct5qerg0N7wo5cGJ1BRU74m4fW" },
  { "id": 33, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون جومبو أخضر", "name_en": "Green Jumbo Asparagus", "description": "هليون أخضر جامبو، ذو سيقان سميكة وعصيرية، يتميز بنكهة قوية وقوام ممتاز.", "features": "حجم كبير يضمن قواماً لذيذاً، غني بالألياف، طبق جانبي فاخر", "origin": "مستورد", "price": 55.0, "price_unit": "ريال للكيلو", "image_url": "1tm5_uSrUWrcmo81hRRGUTLEx5aAKNMtr" },
  { "id": 34, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون أخضر", "name_en": "Green Asparagus", "description": "هليون أخضر طازج، سيقان متوسطة الحجم، نكهة متوازنة وقوام مقرمش.", "features": "مثالي للسلق أو التبخير، غني بالفيتامينات، نكهة ربيعية منعشة", "origin": "مستورد", "price": 50.0, "price_unit": "ريال للكيلو", "image_url": "167yGAK6jXRmCajWB1xJp3Ef8tSP9uFQt" },
  { "id": 35, "category": "الخضروات المستوردة والخاصة", "name_ar": "هليون أبيض", "name_en": "White Asparagus", "description": "هليون أبيض فاخر، يزرع تحت التربة لمنعه من التمثيل الضوئي.", "features": "أغلى وأندر من الأخضر، نكهة خفيفة وحلوة، تقديم فاخر", "origin": "مستورد", "price": 70.0, "price_unit": "ريال للكيلو", "image_url": "10GcG_O49Mw_anzHoljvUSgZrJqNJoWBW" },
  { "id": 36, "category": "الخضروات المستوردة والخاصة", "name_ar": "أفوكادو (USA)", "name_en": "Avocado (USA)", "description": "أفوكادو أمريكي فاخر، ذو قشرة خشنة وقوام كريمي ونكهة غنية.", "features": "غني بالدهون الصحية، حجم كبير، مثالي للتحضيرات اليومية الصحية", "origin": "الولايات المتحدة الأمريكية", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "1QBOHx9NXpKUoIcjSgsboYiEHAGCbnU17" },
  { "id": 37, "category": "الخضروات المستوردة والخاصة", "name_ar": "جزر بيبي (هولندا)", "name_en": "Baby Carrot (Holland)", "description": "جزر بيبي هولندي صغير الحجم، مقرمش وحلو المذاق. معبأ بشكل مثالي.", "features": "مثالي للوجبات الخفيفة، غني بفيتامين A، جاهز للأكل طازجاً", "origin": "هولندا", "price": 20.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "1ApP9hEDNrYBjXZzJBey2RZXIen111w7o" },
  { "id": 38, "category": "الخضروات المستوردة والخاصة", "name_ar": "ذرة بيبي", "name_en": "Baby Corn", "description": "ذرة بيبي صغيرة الحجم، كاملة وكوز صغير، ذات قرمشة عالية.", "features": "مثالية للقلي السريع في الأطباق الآسيوية، غنية بالألياف", "origin": "مستورد (تايلاند عادة)", "price": 5.0, "price_unit": "ريال (للعبوة - PKT)", "image_url": "1yJDrlBc7U2NuWFAZ50X-wTmHnCwjhNvq" },
  { "id": 39, "category": "الخضروات المستوردة والخاصة", "name_ar": "سبانخ بيبي", "name_en": "Baby Spinach", "description": "سبانخ بيبي طازجة، أوراق صغيرة وطرية، ذات نكهة خفيفة وحلوة.", "features": "غنية بالحديد والفيتامينات، جاهزة للأكل دون تقطيع، للسلطات والسموذي", "origin": "مستورد", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "1_P2xKkldJTcKvnwtRKi2NaB01lgIiShQ" },
  { "id": 40, "category": "الخضروات المستوردة والخاصة", "name_ar": "براعم فاصوليا", "name_en": "Bean Sprouts", "description": "براعم فاصوليا طازجة، بيضاء ومقرمشة، ذات نكهة منعشة.", "features": "منخفضة السعرات، غنية بالماء، تضاف للأطباق الآسيوية والسلطات", "origin": "مستورد", "price": 8.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "1zRPAmN9PTYv8ovcWvRSk_CNJ1HVRG3sO" },
  { "id": 41, "category": "الخضروات المستوردة والخاصة", "name_ar": "فاصوليا هاريكوت", "name_en": "Haricot Beans", "description": "فاصوليا هاريكوت خضراء فرنسية، رفيعة وطرية، تعتبر من أفخر الأنواع.", "features": "قوام دقيق ونكهة ممتازة، تطهى بسرعة، طبق جانبي أنيق", "origin": "مستورد", "price": 9.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "1SnXk4MtKvuJsVzD8Pmlegyt3P10U7NdI" },
  { "id": 42, "category": "الخضروات المستوردة والخاصة", "name_ar": "بنجر تشيوجيا", "name_en": "Chioggia Beetroot", "description": "بنجر تشيوجيا الإيطالي، يتميز بلونه الداخلي المخطط بالأحمر والأبيض.", "features": "نكهة حلوة خفيفة، يضيف لمسة جمالية مذهلة للسلطات عند التقطيع", "origin": "إيطاليا (مستورد)", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "11mYSHtKdgc1GGv2gq8Wg8Sl64MZqmrqz" },
  { "id": 43, "category": "الخضروات المستوردة والخاصة", "name_ar": "بنجر ميني أصفر", "name_en": "Mini Yellow Beetroot", "description": "بنجر أصفر صغير الحجم، بلون ذهبي جذاب ونكهة حلوة معتدلة.", "features": "لا يسبب تلطيخ اليدين، غني بالفيتامينات، يضيف لوناً مميزاً للأطباق", "origin": "مستورد", "price": 22.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "15a9YL3HHH87RoO1xYkfJmbPUshmmnDnx" },
  { "id": 44, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل أخضر مستورد", "name_en": "Imported Green Pepper", "description": "فلفل أخضر مستورد، كبير الحجم وذو جدار سميك، يتميز بقرمشته العالية.", "features": "مثالي للحشو والسلطات، جودة تصدير ممتازة، نكهة منعشة", "origin": "مستورد", "price": 27.0, "price_unit": "ريال للكيلو", "image_url": "11Yhc6gFqykDUql5yPHcTbZJBXbkta3xw" },
  { "id": 45, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب برسلز", "name_en": "Brussels Sprouts", "description": "كرنب برسلز طازج، برؤوس صغيرة الحجم تشبه الملفوف المصغر.", "features": "غني بفيتامين C وK، مثالي للشوي والتحميص مع زيت الزيتون", "origin": "مستورد", "price": 25.0, "price_unit": "ريال للكيلو", "image_url": "17l6ZxUG15J6tYIYgmFRldPJthAbOoBsa" },
  { "id": 46, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب صيني", "name_en": "Chinese Cabbage", "description": "كرنب صيني طازج، برأس طويل وأوراق خضراء فاتحة، يتميز بقوامه المقرمش.", "features": "مثالي للسلطات والقلي السريع، أساسي في المطبخ الآسيوي، غني بالألياف", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "1DC5mrOuWJJLRtzjz41phjiFiT6_8B5TJ" },
  { "id": 47, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب أبيض مستورد", "name_en": "Imported White Cabbage", "description": "ملفوف أبيض مستورد، برأس كبير ومتماسك، أوراقه مقرمشة ولذيذة.", "features": "مثالي للسلطات والمخللات، يحتفظ بجودته لفترة تخزين طويلة", "origin": "مستورد", "price": 17.0, "price_unit": "ريال للكيلو", "image_url": "1xiINth0cH4TZgVuCjcbV5XMNqBGPn2gF" },
  { "id": 48, "category": "الخضروات المستوردة والخاصة", "name_ar": "جزر بيبي أحمر", "name_en": "Red Baby Carrot", "description": "جزر بيبي أحمر صغير الحجم، يتميز بلونه الأحمر الجذاب ونكهته الحلوة.", "features": "غني بالأنثوسيانين المضاد للأكسدة، مثالي للوجبات الخفيفة والسلطات", "origin": "مستورد", "price": 8.0, "price_unit": "ريال (للعبوة - PK)", "image_url": "1-fjXdTAGggi-cSHEc1K_8OOxL2TXji-c" },
  { "id": 49, "category": "الخضروات المستوردة والخاصة", "name_ar": "جزر بيبي أصفر", "name_en": "Yellow Baby Carrot", "description": "جزر بيبي أصفر بلون مشمس، حلو المذاق ومقرمش، يضيف لمسة جمالية.", "features": "غني باللوتين، مثالي للأكل الطازج أو التحميص، يحتفظ بلونه", "origin": "مستورد", "price": 36.0, "price_unit": "ريال للكيلو", "image_url": "1lYs8DeAlikDxVBntWJD1TQP0_sbAfwwV" },
  { "id": 50, "category": "الخضروات المستوردة والخاصة", "name_ar": "جذور كرفس بيضاء", "name_en": "Celeriac White", "description": "جذور كرفس بيضاء، نكهة عطرية مميزة تشبه الكرفس مع لمسة جوزية.", "features": "مثالية للحساء والمهروس والسلطات، غنية بالألياف، مطبوخة أو نيئة", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "1xH4n-xdLjK69DqaYA0fK9Kxvrxzv2IjE" },
  { "id": 51, "category": "الخضروات المستوردة والخاصة", "name_ar": "شايوت أخضر", "name_en": "Chayote Green", "description": "شايوت أخضر طازج، ثمرة على شكل كمثرى بلون أخضر فاتح، قوام مقرمش.", "features": "منخفض السعرات، غني بالماء، مثالي للسلطات والقلي والطبخ", "origin": "مستورد", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "1OCsvms2eAN5cgiRs2-83ql_ZU5tkZh2Z" },
  { "id": 52, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو أخضر", "name_en": "Green Jalapeño", "description": "فلفل جالابينو أخضر طازج، يتميز بحرارته المتوسطة ونكهته المميزة.", "features": "حرارة متوازنة، مقرمش، مثالي للصلصات والمخللات المكسيكية", "origin": "مستورد", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "1edFzrDsUouVb2Sd8g2s4WqFcfTVvDgSN" },
  { "id": 53, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو أحمر", "name_en": "Red Jalapeño", "description": "فلفل جالابينو أحمر، هو النسخة الناضجة، يتميز بحلاوة إضافية مع الحرارة.", "features": "أقل حدة قليلاً من الأخضر، لون جميل، مثالي للصلصات والسلطات الحارة", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "1dBnqpPsPrUZa3dw11hsGbMrLvRkwFFdk" },
  { "id": 54, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو أصفر", "name_en": "Yellow Jalapeño", "description": "فلفل جالابينو أصفر نادر، يتميز بلونه الزاهي ونكهته الحارة الفاكهية.", "features": "حرارة متوسطة، مثالي لإضفاء لون ونكهة مميزة للأطباق العالمية", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "12Tc7QQyuDPCvpfWS-erUG2ukz8clIoaq" },
  { "id": 55, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل جالابينو برتقالي", "name_en": "Orange Jalapeño", "description": "فلفل جالابينو برتقالي، صنف نادر وجذاب، حرارة متوازنة.", "features": "يضفي لوناً برتقالياً جميلاً للأطباق، مثالي للتخليل والصلصات المبتكرة", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "1J51PUKxU35P1HHUSoNtEAj6ZYRCONN33" },
  { "id": 56, "category": "الخضروات المستوردة والخاصة", "name_ar": "فلفل أصفر روماني", "name_en": "Roman Yellow Pepper", "description": "فلفل رومي أصفر طويل، يتميز بشكل المستطيل ونكهته الحلوة جداً.", "features": "مثالي للحشو والسلطات، قوام مقرمش، طعم حلو ولذيذ وفاخر", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "19w4IMkjZJtPTgpI4rlS3hYiXIwXDKNmA" },
  { "id": 57, "category": "الخضروات المستوردة والخاصة", "name_ar": "ذرة بيبي طازجة", "name_en": "Fresh Baby Corn", "description": "ذرة بيبي طازجة تماماً، صغيرة الحجم، ذات قرمشة عالية وحلاوة طبيعية.", "features": "طازجة وليست معلبة، مثالية للقلي السريع، منتج توريد فاخر", "origin": "مستورد (تايلاند)", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "1dm0CSMgIGrGALhWU2buHi_AGcD4-hqMV" },
  { "id": 58, "category": "الخضروات المستوردة والخاصة", "name_ar": "خيار طويل مستورد", "name_en": "Imported Long Cucumber", "description": "خيار طويل مستورد، ذو قشرة رقيقة وبذور قليلة، مقرمش جداً.", "features": "مثالي للسلطات والتقطيع، قوام متماسك، جودة تصدير من الدرجة الأولى", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "1rkdNPusbCQykaof3t68_YPAaCXgbkzxA" },
  { "id": 59, "category": "الخضروات المستوردة والخاصة", "name_ar": "فول فافا طازج", "name_en": "Fresh Fava Beans", "description": "فول فافا طازج في قرونه الخضراء، يتميز بحباته الكبيرة ونكهته الزبدية.", "features": "غني بالبروتين والألياف، مثالي للطهي مع اللحوم أو التحضير التقليدي", "origin": "مستورد", "price": 39.0, "price_unit": "ريال للكيلو", "image_url": "1J2GvJM34BTqacQqggTX47uWJfagGVcZb" },
  { "id": 60, "category": "الخضروات المستوردة والخاصة", "name_ar": "فينل بيبي (شمر)", "name_en": "Baby Fennel", "description": "شمر بيبي صغير الحجم، ذو نكهة عرق السوس الخفيفة وقوام مقرمش.", "features": "مثالي للشوي والسلطات، الأوراق تستخدم كزينة، نكهة منعشة وفريدة", "origin": "مستورد", "price": 21.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "14AL1uDa52BgwK_zjkJV2Z9DfFqKGk7AY" },
  { "id": 61, "category": "الخضروات المستوردة والخاصة", "name_ar": "كولرابي مستورد", "name_en": "Imported Kohlrabi", "description": "كولرابي طازج، يشبه اللفت بنكهة الفجل الحلو. مقرمش ولذيذ.", "features": "يمكن تناوله نيئاً مع قليل من الملح، غني بفيتامين C، مثالي للسلطات", "origin": "مستورد", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "1S-ujNlqDlUOR7Xh-81v920vPGSnuD4jg" },
  { "id": 62, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر بوتون بني", "name_en": "Brown Button Mushroom", "description": "فطر بوتون بني طازج، يتميز بنكهة أقوى من الأبيض وقوام متماسك.", "features": "نكهة ترابية أغنى، مثالي للشوي والصلصات، غني بالفيتامينات", "origin": "مستورد", "price": 25.0, "price_unit": "ريال للكيلو", "image_url": "1rrwWMlGefEXm5usD-1AHOed6AZ9bBjHa" },
  { "id": 63, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر بورشيني", "name_en": "Porcini Mushroom", "description": "فطر بورشيني الفاخر، ذو نكهة قوية وغنية جداً تعتبر من أفخر النكهات.", "features": "نكهة جوزية مميزة، مثالي للريزوتو والصلصات الكريمية، منتج فاخر", "origin": "مستورد (إيطالي عادة)", "price": 85.0, "price_unit": "ريال للكيلو", "image_url": "1Fk2P6u4MfCr14-fCD5_5ewg5PdwLhAuR" },
  { "id": 64, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر كستناء", "name_en": "Chestnut Mushroom", "description": "فطر كستناء طازج، بلون بني داكن ونكهة ترابية غنية. قوام متماسك.", "features": "مثالي للشوي والتحمير، يحتفظ بقوامه بعد الطهي، نكهة مميزة", "origin": "مستورد", "price": 30.0, "price_unit": "ريال للكيلو", "image_url": "1eTAM3B6n4UNyeN-QxGh7tBu2qQ5vHPvX" },
  { "id": 65, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر إنوكي", "name_en": "Enoki Mushroom", "description": "فطر إنوكي أبيض نحيل طويل، برؤوس صغيرة، قوام مقرمش ونكهة خفيفة.", "features": "يضاف في آخر الطهي، مثالي للشوربات والقلي السريع الآسيوي", "origin": "مستورد", "price": 20.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "1QnK_9-v7m3V5hzWmQ8B09W54juKJZG0y" },
  { "id": 66, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر بورتوبيلو", "name_en": "Portobello Mushroom", "description": "فطر بورتوبيلو كبير الحجم، ذو قبعة عريضة ونكهة غنية ولحمية.", "features": "بديلاً ممتازاً للحم، مثالي للشوي كاملة، يمكن حشوها، نكهة قوية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1Zd4cnwC3kWN4L7Jg1Epe-NJkOAWg7jzK" },
  { "id": 67, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر شيتاكي", "name_en": "Shiitake Mushroom", "description": "فطر شيتاكي آسيوي، ذو قبعة بنية ونكهة مدخنة غنية.", "features": "غني بالعناصر الغذائية، مثالي للقلي السريع واليخنات، نكهة أومامي", "origin": "مستورد", "price": 74.0, "price_unit": "ريال للكيلو", "image_url": "1Kw0krn3FIsEcNq8fr9rVf_Iy8T3F30hi" },
  { "id": 68, "category": "الخضروات المستوردة والخاصة", "name_ar": "فطر شيميجي أبيض", "name_en": "White Shimeji Mushroom", "description": "فطر شيميجي أبيض صغير الحجم، ينمو في عناقيد، نكهة جوزية خفيفة.", "features": "مثالي للقلي السريع، لا يحتاج لتقطيع، يضيف نكهة رائعة للأطباق", "origin": "مستورد", "price": 48.0, "price_unit": "ريال للكيلو", "image_url": "1V-HWVi4JjF8_8hCT2rFnyR3m62uZG-Zh" },
  { "id": 69, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل لؤلؤي أحمر", "name_en": "Red Pearl Onion", "description": "بصل لؤلؤي أحمر صغير جداً، بحجم حبة الكرز، يتميز بحلاوته.", "features": "حجم صغير مثالي للتقديم الفاخر، نكهة حلوة خفيفة، للشوي الكامل", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "1QhVgwtXFk2eBWjVhuter5uxFsC4EpPaE" },
  { "id": 70, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل لؤلؤي أبيض", "name_en": "White Pearl Onion", "description": "بصل لؤلؤي أبيض صغير، بنفس حجم الأحمر، يتميز بنكهة معتدلة.", "features": "مثالي لتحضير اليخنات الصغيرة أو التحميص، يضيف لمسة فاخرة", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "1K3-TvxAy-QlMzUEraf1oyBBb2VwcmtR5" },
  { "id": 71, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل أحمر جومبو", "name_en": "Jumbo Red Onion", "description": "بصل أحمر جامبو كبير الحجم، يتميز بحجمه الضخم ونكهته القوية.", "features": "حجم كبير يقلل الهدر في المطابخ الكبرى، نكهة ممتازة للطبخ والشوي", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "14GlYI14b3gD71C_a2e8px8HkcjCrllEX" },
  { "id": 72, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل شالوت", "name_en": "Shallots", "description": "بصل شالوت، يتميز بشكل مستطيل ونكهة خفيفة وحلوة بين البصل والثوم.", "features": "أساسي في المطبخ الفرنسي، نكهة دقيقة لا تطغى على الأطباق", "origin": "مستورد", "price": 24.0, "price_unit": "ريال للكيلو", "image_url": "1LwEILvV5iYihZkqTEmUuS64B4LCtnzp3" },
  { "id": 73, "category": "الخضروات المستوردة والخاصة", "name_ar": "بصل أبيض مستورد", "name_en": "Imported White Onion", "description": "بصل أبيض مستورد كبير الحجم، يتميز بقشرته البيضاء الناصعة.", "features": "جودة عالية، حجم مناسب، نكهة قوية مثالية للطبخ اليومي والمطاعم", "origin": "مستورد", "price": 15.0, "price_unit": "ريال للكيلو", "image_url": "1UQyjcUN0ijNNYA2HMGl39A3l3O3Tl3q8" },
  { "id": 74, "category": "الخضروات المستوردة والخاصة", "name_ar": "بازلاء خضراء", "name_en": "Green Peas", "description": "بازلاء خضراء طازجة في قرونها، حباتها ممتلئة وحلوة الطعم.", "features": "غنية بالبروتين النباتي، قطف طازج يضمن أفضل نكهة طبيعية وحلاوة", "origin": "مستورد", "price": 29.0, "price_unit": "ريال للكيلو", "image_url": "19XXkbPBy9mJde_6HU5l1DwRYlvefM47X" },
  { "id": 75, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس بيبي", "name_en": "Baby Potato", "description": "بطاطس بيبي صغيرة الحجم، بقشرة رقيقة ونكهة زبدية.", "features": "لا تحتاج تقشير، مثالية للسلق أو الشوي كاملة، قوام كريمي لذيذ", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "1A5KEerGGxvERhVXiH2Y-H3227t4fV6j_" },
  { "id": 76, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس بيبي حمراء", "name_en": "Red Baby Potato", "description": "بطاطس بيبي حمراء صغيرة، بقشرة حمراء رقيقة، قوام شمعي.", "features": "يحافظ على شكله بعد الطهي، مثالية للسلطات والسلق، نكهة ممتازة", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "1wogGl5ZyzVDFM521GkVt5oTeasdN35Bg" },
  { "id": 77, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس بيبي بيضاء", "name_en": "White Baby Potato", "description": "بطاطس بيبي بيضاء صغيرة، بقشرة بيضاء ناعمة، ذات نكهة خفيفة.", "features": "قوام كريمي، سريعة الطهي، مثالية للتحميص مع الأعشاب والزبدة", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "1xZ95wu_YSlOnh3RjSBn5OfYUeNDGGDFh" },
  { "id": 78, "category": "الخضروات المستوردة والخاصة", "name_ar": "بطاطس حلوة (USA)", "name_en": "Sweet Potato (USA)", "description": "بطاطا حلوة أمريكية، ذات لون برتقالي زاهي من الداخل.", "features": "حلاوة طبيعية، غنية بفيتامين A، قوام كريمي، بديل صحي وممتاز", "origin": "الولايات المتحدة الأمريكية", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "1ZIVxLfgQAnIgZgZ_7ZZWY-ySgz2NWCmr" },
  { "id": 79, "category": "الخضروات المستوردة والخاصة", "name_ar": "رومانيسكو ميني", "name_en": "Mini Romanesco", "description": "رومانيسكو ميني، نوع فاخر من القرنبيط ذو شكل حلزوني هندسي مذهل.", "features": "نكهة دقيقة، شكل جمالي رائع، لون أخضر ليموني، مثالي للتبخير", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "14-W6OmG2SCXH9q-6cJ_QRsYY0iP1VGN6" },
  { "id": 80, "category": "الخضروات المستوردة والخاصة", "name_ar": "كرنب سافوي", "name_en": "Savoy Cabbage", "description": "كرنب سافوي بأوراقه المجعدة الخضراء الداكنة، قوام طري.", "features": "نكهة معتدلة، أوراق مرنة مثالية للحشو، ألذ من الملفوف العادي", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "1eOoSWMU7hdkUaHEsOAchodiXnXstWo9A" },
  { "id": 81, "category": "الخضروات المستوردة والخاصة", "name_ar": "بازلاء الثلج", "name_en": "Snow Peas", "description": "بازلاء الثلج طازجة، قرونها مسطحة وبها بذور صغيرة جداً.", "features": "تؤكل كاملة، قرمشة عالية ونكهة حلوة، غنية بالألياف، للسلطات", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "1XwERIaY_F2oVbXUcb_v8QGq8ljOspVQW" },
  { "id": 82, "category": "الخضروات المستوردة والخاصة", "name_ar": "قرع أكرون أخضر", "name_en": "Green Akron Squash", "description": "قرع أكرون أخضر على شكل بلوط، بقشرة خضراء داكنة مجعدة.", "features": "لحم برتقالي حلو، مثالي للشوي أو الخبز، حجم صغير لفرد واحد", "origin": "مستورد", "price": 26.0, "price_unit": "ريال للكيلو", "image_url": "1fp6ArUqVjQjIu8L7_BB6Af-cW2XhGExR" },
  { "id": 83, "category": "الخضروات المستوردة والخاصة", "name_ar": "قرع باترنوت", "name_en": "Butternut Squash", "description": "قرع باترنوت بشكل كمثرى، بلون بيج من الخارج ولحم برتقالي حلو.", "features": "قوام كريمي، مثالي للحساء والمهروس، سهل التقشير، غني بفيتامين A", "origin": "مستورد", "price": 21.0, "price_unit": "ريال للكيلو", "image_url": "1Vqm5yPh1Wzz0PHYNGj9y1wl79Gym48Pv" },
  { "id": 84, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم كومب برتقالي", "name_en": "Orange Kumquat Tomato", "description": "طماطم كومب برتقالية صغيرة الحجم، تشبه حبات البرتقال الصغيرة.", "features": "حلاوة عالية جداً، لون زاهي، مثالية للسلطات الفاخرة والمقبلات", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "1NfBuu1NVM_7j-khpMHSDufsuGiEj2pge" },
  { "id": 85, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم كومب حمراء", "name_en": "Red Kumquat Tomato", "description": "طماطم كومب حمراء صغيرة الحجم، على شكل حبات صغيرة.", "features": "نكهة طماطم غنية وحلاوة متوازنة، قوام متماسك، طعم ممتاز وفريد", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1xq4C7ZcdurD4md1eRaCumsUt0L0yY7wm" },
  { "id": 86, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم كرزية صفراء", "name_en": "Yellow Cherry Tomato", "description": "طماطم كرزية صفراء صغيرة الحجم، بلون أصفر مشمس.", "features": "حلاوة فائقة وقرمشة عالية، أقل حموضة من الحمراء، تضفي لوناً رائعاً", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1bbDw9eWmGksBHzfncuZx3CcxaS5i613e" },
  { "id": 87, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم هيرلوم", "name_en": "Heirloom Tomato", "description": "طماطم هيرلوم تراثية، تتميز بأشكالها وألوانها المتنوعة.", "features": "نكهة استثنائية تشبه طماطم الماضي، غنية ومعقدة، تجربة طعم فريدة", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "1XW76x9Ch9py4sj8WXJp-CtBGlgngFijn" },
  { "id": 88, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم مارماند", "name_en": "Marmande Tomato", "description": "طماطم مارماند فرنسية، كبيرة الحجم ومضلعة، قوام لحمي.", "features": "نكهة قوية، مثالية للحشو والصلصات، لحمية وقليلة البذور، طعم غني", "origin": "فرنسا (مستورد)", "price": 40.0, "price_unit": "ريال للكيلو", "image_url": "1p5fCQqMiCkXM4aEcmczZGJmWEmVn9gUV" },
  { "id": 89, "category": "الخضروات المستوردة والخاصة", "name_ar": "طماطم روما بلوم", "name_en": "Roma Plum Tomato", "description": "طماطم روما بلوم بشكل بيضاوي، لحمية وقليلة العصارة.", "features": "مثالية لصنع الصلصات والمعجون، سهلة التقشير، للطبخ الطويل", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "17_5NDjh9hq0xg0JMRoYzKYL1VR-RsMRC" },
  { "id": 90, "category": "الخضروات المستوردة والخاصة", "name_ar": "كركم طازج", "name_en": "Fresh Turmeric", "description": "كركم طازج بجذور برتقالية زاهية، يشبه الزنجبيل بلون برتقالي.", "features": "مضاد طبيعي للالتهابات، نكهة ترابية خفيفة، للطبخ والعصائر الصحية", "origin": "مستورد", "price": 23.0, "price_unit": "ريال للكيلو", "image_url": "1yq0nlO352FMx_k5a-CXKr5hFO6jQlI_D" },
  { "id": 91, "category": "الخضروات المستوردة والخاصة", "name_ar": "لفت ميني مستورد", "name_en": "Imported Mini Turnip", "description": "لفت ميني مستورد صغير الحجم، بقشرة بيضاء وأرجوانية.", "features": "نكهة حلوة معتدلة وقوام مقرمش، يؤكل بقشرته، للتحميص الكامل", "origin": "مستورد", "price": 122.0, "price_unit": "ريال للكيلو", "image_url": "1Jtl7fRaNHO6kks7Y5McHBJLDJusYS4ds" },
  { "id": 92, "category": "الخضروات المستوردة والخاصة", "name_ar": "كوسا بيبي مع الزهرة", "name_en": "Baby Zucchini with Flower", "description": "كوسا بيبي طازجة مع أزهارها الصفراء الجميلة. منتج أفخر.", "features": "الزهرة صالحة للأكل للحشو والقلي، الكوسا طرية وحلوة وفاخرة", "origin": "مستورد", "price": 27.0, "price_unit": "ريال للكيلو", "image_url": "1UjoEWWdwvTJSxdIaEN6diBDYJlkOigH-" },
  { "id": 93, "category": "الفواكه", "name_ar": "موز", "name_en": "Banana", "description": "موز طازج أصفر ناصع، ذو حلاوة طبيعية وقوام كريمي.", "features": "غني بالبوتاسيوم، طاقة طبيعية سريعة، مثالي للعصائر والوجبات", "origin": "مستورد", "price": 6.5, "price_unit": "ريال للكيلو", "image_url": "1roqilvzW0aFvd72psaUNd6nLVy0llUA1" },
  { "id": 94, "category": "الفواكه", "name_ar": "تفاح سكري", "name_en": "Sukari Apple", "description": "تفاح سكري بلون أحمر وأصفر، حلاوة عالية وقوام مقرمش.", "features": "بدون حموضة، حلاوة طبيعية، مقرمش ومنعش، صنف محلي مفضل", "origin": "إنتاج وطني (محلي)", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "1X7FG7amlFE1_k96uyAI3gM1Q9ejcF9TR" },
  { "id": 95, "category": "الفواكه", "name_ar": "تفاح أخضر", "name_en": "Green Apple", "description": "تفاح أخضر طازج بلون أخضر زاهي، نكهة حامضة منعشة.", "features": "قوام صلب مقرمش، مثالي للسلطات والعصائر الصحية، غني بالألياف", "origin": "مستورد", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "1HYSdbXaI_PdzC5581TZIyscKyj0tDO52" },
  { "id": 96, "category": "الفواكه", "name_ar": "تفاح أحمر", "name_en": "Red Apple", "description": "تفاح أحمر طازج بلون أحمر جذاب، توازن حلاوة وحموضة.", "features": "مقرمش وعصيري، مثالي للأكل اليومي، نكهة محببة للجميع وعالية الجودة", "origin": "مستورد", "price": 7.5, "price_unit": "ريال للكيلو", "image_url": "1iyDPLH7anHuxmpXgUm6aAVRN_CcPDLJE" },
  { "id": 97, "category": "الفواكه", "name_ar": "برتقال عصير", "name_en": "Juice Orange", "description": "برتقال مخصص للعصر، كثير العصارة وحلو المذاق، قشرة رقيقة.", "features": "عصير غني بفيتامين C، مثالي لتحضير العصير الطازج اليومي", "origin": "إنتاج وطني (محلي)", "price": 5.0, "price_unit": "ريال للكيلو", "image_url": "1M3J_PB_1mbs9xlAwT9a--htaSjCxX8Bk" },
  { "id": 98, "category": "الفواكه", "name_ar": "برتقال أبوصورة", "name_en": "Navel Orange", "description": "برتقال أبوصورة (نافل)، حلو المذاق وخالي من البذور.", "features": "سهل التقشير، حلو جداً، مثالي للأكل الطازج كفاكهة يومية", "origin": "مستورد", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "1seTFwfepR25W0uu5R0pFVnxNHHZTimpa" },
  { "id": 99, "category": "الفواكه", "name_ar": "مانجو تيمور", "name_en": "Mango Taimur", "description": "مانجو تيمور، صنف وطني فاخر، نكهة غنية وحلوة.", "features": "لحم سميك وقليل الألياف، رائحة عطرية، من أفضل الأصناف الوطنية", "origin": "إنتاج وطني (محلي)", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "1uSIz8w6s1gArsrSy5T27Sj_z9m7yWC2L" },
  { "id": 100, "category": "الفواكه", "name_ar": "فراولة مصري", "name_en": "Egyptian Strawberry", "description": "فراولة مصرية طازجة، كبيرة الحجم ذات لون أحمر زاهي.", "features": "حلوة وعصيرية، مثالية للحلويات والعصائر الفاخرة، غنية بفيتامين C", "origin": "مصر", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "1K4z4iRwMKNeb4Al35lXM9A-_3WNzq5OF" },
  { "id": 101, "category": "الفواكه", "name_ar": "كيوي", "name_en": "Kiwi", "description": "كيوي طازج، أخضر زاهي من الداخل، نكهة حامضة حلوة.", "features": "منعش، غني بفيتامين C، مثالي للسلطات، يمكن تناوله بملعقة", "origin": "مستورد", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "13l4mjLq2Or2GUWM75AReVkL0-DEh_AAf" },
  { "id": 102, "category": "الفواكه", "name_ar": "عنب أخضر محلي", "name_en": "Local Green Grapes", "description": "عنب أخضر وطني طازج، حبات مقرمشة وحلوة المذاق.", "features": "خالي من البذور تقريباً، حلاوة طبيعية منعشة، محصول محلي طازج", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1TJt8xwRTaXNfZS37bCYsd2H_yMW41-no" },
  { "id": 103, "category": "الفواكه", "name_ar": "أناناس كبير", "name_en": "Large Pineapple", "description": "أناناس كبير الحجم، لحم أصفر عصيري ونكهة استوائية.", "features": "غني بالإنزيمات الهاضمة، حلاوة استوائية منعشة، للعصائر والحلويات", "origin": "مستورد", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "1jj-d1q8SoeTx1abxaTg1J0Ap2_gmgLIG" },
  { "id": 104, "category": "الفواكه", "name_ar": "رمان محلي", "name_en": "Local Pomegranate", "description": "رمان وطني طازج، بقشرة حمراء وحبات ياقوتية لامعة.", "features": "حلاوة عالية، نسبة عصير مرتفعة، غني بمضادات الأكسدة، جمالية في التقديم", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1U1pftSr6wpjlm4mXaJxY6GFVYPnTaDTi" },
  { "id": 105, "category": "الفواكه", "name_ar": "شمام", "name_en": "Sweet Melon", "description": "شمام أخضر فاتح من الخارج، حلاوة منعشة وقوام عصيري.", "features": "طعم حلو ومنعش، غني بالفيتامينات، مثالي للسلطات والحلويات الباردة", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "1V4II-9qM_iB4Nf1ZeRafxRTqN_pxkY1r" },
  { "id": 106, "category": "الفواكه", "name_ar": "بطيخ مدور محلي", "name_en": "Round Watermelon", "description": "بطيخ أحمر مدور وطني، بلحم أحمر غامق، حلو جداً.", "features": "منعش، يروي العطش، غني بالماء، حلاوة طبيعية عالية، مثالي للصيف", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "1GjBJ1-RNCA9PtMjEZU6PQ3lgV45ujiDh" },
  { "id": 107, "category": "الفواكه", "name_ar": "ليمون كبير محلي", "name_en": "Large Local Lemon", "description": "ليمون وطني كبير الحجم، أصفر زاهي، كثير العصارة وحامض.", "features": "غني بفيتامين C، نكهة قوية ومميزة، للعصائر والطبخ والمخللات", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "1G06JpdAVvjewiEklFzjcuAeOsAj2cgE0" },
  { "id": 108, "category": "الفواكه", "name_ar": "ليمون صغير محلي", "name_en": "Small Local Lemon", "description": "ليمون وطني صغير (بنزهير)، قشرة رقيقة ورائحة عطرية.", "features": "حامض جداً ولذيذ، مثالي للمشروبات، يعصر بسهولة، نكهة مركزة", "origin": "إنتاج وطني (محلي)", "price": 4.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "1z0OMKWQhOqUBvGqwnpV_4OCCJscBjUNC" },
  { "id": 109, "category": "الفواكه", "name_ar": "مشمش مستورد (USA)", "name_en": "Imported Apricot", "description": "مشمش أمريكي طازج برتقالي محمر، ناعم وحلو الملمس.", "features": "رائحة عطرية، غني بفيتامين A، للأكل الطازج أو صناعة الحلويات", "origin": "الولايات المتحدة الأمريكية", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1UjqFcXqppEczF3X-VhwA7dK0HFMiVYVk" },
  { "id": 110, "category": "الفواكه", "name_ar": "توت أسود (USA)", "name_en": "Blackberries", "description": "توت أسود أمريكي طازج، حبات كبيرة لامعة، نكهة غنية.", "features": "حامض حلو، غني بمضادات الأكسدة، مثالي للحلويات الراقية والعصائر", "origin": "الولايات المتحدة الأمريكية", "price": 15.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "1sLXKMwSsFDZQ03x4-NxXjoZ0912qPURI" },
  { "id": 111, "category": "الفواكه", "name_ar": "توت أزرق مستورد", "name_en": "Blueberries", "description": "توت أزرق طازج، حبات صغيرة داكنة، نكهة حلوة حمضية.", "features": "سوبر فود، غني بمضادات الأكسدة، مثالي للإفطار والحلويات الصحية", "origin": "مستورد", "price": 14.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "1eILz1cPmV30ryMqXyFPb8cVWcp_EC7Wg" },
  { "id": 112, "category": "الفواكه", "name_ar": "شمام كانتالوب", "name_en": "Cantaloupe Melon", "description": "شمام كانتالوب بلحم برتقالي، رائحة عطرية وحلاوة عالية.", "features": "طعم غني وحلو، غني بفيتامين A، مثالي للسلطات والتحلية", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "1bdz3NXs3EwWLbqWbnxHQsT_06Pa2gjo1" },
  { "id": 113, "category": "الفواكه", "name_ar": "كرز مستورد (USA)", "name_en": "Cherry (USA)", "description": "كرز أمريكي طازج، بلون أحمر غامق، حلاوة فائقة وقوام صلب.", "features": "فاكهة فاخرة، حجم كبير، مثالية للتقديم والمناسبات، نكهة مركزة", "origin": "الولايات المتحدة الأمريكية", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "1BPQexBwvFIJtc1YwBFnvrw9ULJZ29QX-" },
  { "id": 114, "category": "الفواكه", "name_ar": "كرز أسترالي", "name_en": "Australian Cherry", "description": "كرز أسترالي فاخر، بلون أحمر غامق، حلاوة وقرمشة عالية.", "features": "أجود أنواع الكرز، حجم كبير جداً، نكهة استثنائية وفريدة", "origin": "أستراليا", "price": 50.0, "price_unit": "ريال للكيلو", "image_url": "1LtjnlfwJfzIsB9MbJTWX_5NJQ3u4Wpld" },
  { "id": 115, "category": "الفواكه", "name_ar": "كرانبيري طازج", "name_en": "Fresh Cranberry", "description": "توت الكرانبيري الطازج بلون أحمر داكن، طعم حامض مميز.", "features": "غني بمضادات الأكسدة، للصلصات والعصائر والمخبوزات الصحية", "origin": "مستورد", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "1w9OZhBSGiQpPa0dK2CuBR1ofvC4hzHJa" },
  { "id": 116, "category": "الفواكه", "name_ar": "ثمرة التنين", "name_en": "Dragon Fruit", "description": "فاكهة التنين الجذابة، قشرة وردية ولب عصيري حلو.", "features": "مظهر رائع، غنية بالألياف، منخفضة السعرات، للسلطات والعصائر", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "1-rvuAMisOVATOCHikvLVYXgRcwOxcwSv" },
  { "id": 117, "category": "الفواكه", "name_ar": "دوريان مستورد", "name_en": "Imported Durian", "description": "دوريان، ملك الفواكه، قشرة شوكية ولب كريمي غني.", "features": "نكهة فريدة وقوية جداً، غني بالطاقة، قوام زبدي دسم وفارخ", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "1Hwc0mzLETnhjSq53wmdbDWv-sRYKABiH" },
  { "id": 118, "category": "الفواكه", "name_ar": "كمثرى فوريل", "name_en": "Forelle Pear", "description": "كمثرى فوريل صغيرة، لون أصفر بنقاط حمراء، نكهة حلوة منعشة.", "features": "قوام مقرمش، حجم مثالي، قشرة رقيقة وطعم ممتاز للأطفال", "origin": "مستورد", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "1OPBiCfjhpZ6l6T4YBcocQFvO2HiCYHqS" },
  { "id": 119, "category": "الفواكه", "name_ar": "غرانديلا مستوردة", "name_en": "Imported Grandilla", "description": "غرانديلا (العاطفة الحلوة)، قشرة برتقالية صلبة ولب حلو.", "features": "نكهة استوائية رائعة، تؤكل بملعقة، غنية بالفيتامينات وبذور مقرمشة", "origin": "مستورد", "price": 33.0, "price_unit": "ريال للكيلو", "image_url": "1s_4d_VkUGdy11EcVJiVTIkiV51Vz8cA6" },
  { "id": 120, "category": "الفواكه", "name_ar": "جريب فروت وردي", "name_en": "Pink Grapefruit", "description": "جريب فروت وردي كبير، لب وردي ونكهة حامضة مرة منعشة.", "features": "غني بفيتامين C، مثالي للإفطار الصحي والعصائر المنعشة للجسم", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "1TqO8-6Ab8aWmika4X7N-H_unQ3boZRmt" },
  { "id": 121, "category": "الفواكه", "name_ar": "شمام هوني ديو", "name_en": "Honeydew Melon", "description": "شمام هوني ديو أخضر فاتح، حلاوة عالية جداً وقوام عصيري.", "features": "حلاوة مركزة، منعش، مثالي للحلويات الصيفية وسلطات الفواكه", "origin": "مستورد", "price": 22.0, "price_unit": "ريال للكيلو", "image_url": "1ychMv5nsiKpV5U7dGE_OEzHfjKKqgnC6" },
  { "id": 122, "category": "الفواكه", "name_ar": "كيوانو هولندا", "name_en": "Kiwano (Holland)", "description": "كيوانو بقشرة برتقالية شوكية ولب أخضر منعش.", "features": "شكل غريب وجذاب، نكهة خيار وموز، غني بالماء ومنعش جداً", "origin": "هولندا", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "1gReHQ2gWbcD_VMNFZ_FW_bNl-lKpCLYY" },
  { "id": 123, "category": "الفواكه", "name_ar": "كومكوات مستورد", "name_en": "Imported Kumquat", "description": "كومكوات (برتقال ذهبي) صغير، يؤكل بقشره، نكهة حلوة حامضة.", "features": "تؤكل كاملة، مثالية للمربى أو التزيين، غنية جداً بفيتامين C", "origin": "مستورد", "price": 52.0, "price_unit": "ريال للكيلو", "image_url": "1jALfmoDOcdH_qcgXcRCTqHpzyu50Frmg" },
  { "id": 124, "category": "الفواكه", "name_ar": "لونغان مستورد", "name_en": "Imported Longan", "description": "لونغان (عين التنين) فاكهة استوائية صغيرة حلوة.", "features": "لب شفاف حلو، تشبه الليتشي، منعشة ومثالية كوجبة خفيفة استوائية", "origin": "مستورد", "price": 37.0, "price_unit": "ريال للكيلو", "image_url": "1wNeETi8Bo7SkRrR_p-gMVPdJ7_5yeYkH" },
  { "id": 125, "category": "الفواكه", "name_ar": "ليتشي مستورد", "name_en": "Imported Lychee", "description": "ليتشي طازج بقشرة خشنة ولب أبيض عصيري.", "features": "نكهة زهرية حلوة، فاكهة صيفية فاخرة، غنية جداً بفيتامين C", "origin": "مستورد", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "1_gVMe9Zi_J0N_K0JWLJ2ydCDYqL9g1xi" },
  { "id": 126, "category": "الفواكه", "name_ar": "مانغوستين مستورد", "name_en": "Imported Mangosteen", "description": "مانغوستين، ملكة الفواكه، لب أبيض ناعم وحلو حامض.", "features": "لب يذوب في الفم، غني بمضادات الأكسدة، فاكهة استوائية فاخرة", "origin": "مستورد", "price": 36.0, "price_unit": "ريال للكيلو", "image_url": "1qjEwr0aPZcnD3M9eiJsJTAdC0J4ec6b0" },
  { "id": 127, "category": "الفواكه", "name_ar": "نكتارين (USA)", "name_en": "Nectarine (USA)", "description": "نكتارين أمريكي، قشرة ناعمة وحلاوة مركزة.", "features": "قوام صلب مقرمش، نكهة حلوة قوية، مثالي للأكل الطازج، غني بالفيتامينات", "origin": "الولايات المتحدة الأمريكية", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "1BFzIYm5TA1hE1dJfqGi78ovEdFIJnRY0" },
  { "id": 128, "category": "الفواكه", "name_ar": "باسيون فروت", "name_en": "Passion Fruit", "description": "فاكهة العاطفة، لب أصفر وبذور مقرمشة، نكهة استوائية عطرية.",
    "features": "نكهة حامضة حلوة قوية، مثالية للصلصات والعصائر والحلويات الفاخرة", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1EX5AgbN8N5GHO6psE-RRyqYMKjaDD4SD" },
  { "id": 129, "category": "الفواكه", "name_ar": "خوخ مستورد (USA)", "name_en": "Imported Peach", "description": "خوخ أمريكي طازج، بلون أصفر محمر وحلاوة عالية.", "features": "عصيري، غني بالألياف، نكهة صيفية رائعة، مثالي للأكل والحلويات", "origin": "الولايات المتحدة الأمريكية", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "1mgGWLShqVUl-qozkjHItXuUeo4L8Ci8b" },
  { "id": 130, "category": "الفواكه", "name_ar": "فيزاليس (حرنكش)", "name_en": "Physalis", "description": "فيزاليس بقشرة ورقية، ثمرة صغيرة برتقالية حامضة حلوة.", "features": "غني بفيتامين C، مثالي لتزيين الحلويات الراقية، نكهة فريدة ومميزة", "origin": "مستورد", "price": 65.0, "price_unit": "ريال للكيلو", "image_url": "16n_6R1i7WrNq234llyTr25uy6hMjJBa4" },
  { "id": 131, "category": "الفواكه", "name_ar": "رامبوتان مستورد", "name_en": "Imported Rambutan", "description": "رامبوتان بقشرة حمراء شعيرية ولب أبيض حلو.", "features": "سهل التقشير، نكهة استوائية منعشة تشبه الليتشي، مظهر جذاب جداً", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1gW8FspMbroImfvY4A6VentUukMk4uN0l" },
  { "id": 132, "category": "الفواكه", "name_ar": "توت أحمر مستورد", "name_en": "Red Raspberries", "description": "توت أحمر طازج، بلون أحمر زاهي ونكهة حلوة حمضية.", "features": "غني بمضادات الأكسدة، مثالي للحلويات والتزيين الفاخر، نكهة مميزة", "origin": "مستورد", "price": 15.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "1MnbyNPZJvTDc3J6rLmqW1GiT7KJOHtm5" },
  { "id": 133, "category": "الفواكه", "name_ar": "كشمش أحمر", "name_en": "Red Currants", "description": "كشمش أحمر طازج، حبات حمراء شفافة في عناقيد.", "features": "نكهة حامضة منعشة، مثالي لصنع الجيلي والمربى وتزيين الحلويات", "origin": "مستورد", "price": 17.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "1JRl76eH9z2Ozm929C8e5Lb8gsZ0sjv0a" },
  { "id": 134, "category": "الفواكه", "name_ar": "فاكهة النجمة", "name_en": "Star Fruit", "description": "فاكهة النجمة (كارامبولا)، شكل نجمة عند التقطيع.", "features": "لون أصفر، نكهة حامضة حلوة، جمالية رائعة لتزيين الكوكتيل والسلطات", "origin": "مستورد", "price": 90.0, "price_unit": "ريال للكيلو", "image_url": "1Nh9ylpYZAZQwXNEafKPRya6FYzLRWo6D" },
  { "id": 135, "category": "الفواكه", "name_ar": "فراولة (USA)", "name_en": "Strawberry (USA)", "description": "فراولة أمريكية فاخرة، كبيرة الحجم وحلوة جداً.", "features": "جودة عالية، عصيرية، لون أحمر زاهي، مثالية للحلويات الفاخرة", "origin": "الولايات المتحدة الأمريكية", "price": 47.0, "price_unit": "ريال للكيلو", "image_url": "1xKFqKZ50iW5VPNeM3GBwfpWX_UXBV6I6" },
  { "id": 136, "category": "الفواكه", "name_ar": "تاماريلو مستورد", "name_en": "Imported Tamarillo", "description": "تاماريلو (شجرة الطماطم)، لب حامض حلو يشبه الطماطم.", "features": "تؤكل بعد التقشير، غنية بالفيتامينات، مثالية للعصائر والصلصات", "origin": "مستورد", "price": 53.0, "price_unit": "ريال للكيلو", "image_url": "1XfNIUd9-Y0TPx061m_LSRhlXM8NVUlyZ" },
  { "id": 137, "category": "الفواكه", "name_ar": "نكتارين محلي", "name_en": "Local Nectarine", "description": "نكتارين وطني طازج، قشرة ناعمة وحلاوة طبيعية.", "features": "محصول محلي طازج، نكهة رائعة، مثالي للأكل اليومي، جودة عالية", "origin": "إنتاج وطني (محلي)", "price": 16.0, "price_unit": "ريال للكيلو", "image_url": "1LxSawXI1tHImhF7qscyOgZLVpm2SYxJm" },
  { "id": 138, "category": "الفواكه", "name_ar": "بخارة أسود", "name_en": "Black Plum", "description": "بخارة سوداء (برقوق) طازجة، نكهة حلوة مع حموضة خفيفة.", "features": "قوام عصيري، غنية بالألياف، مثالية كوجبة خفيفة صحية ومفيدة", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1QqQQpYsP--x7Nz3vsCmhElPy-NJBLe55" },
  { "id": 139, "category": "الفواكه", "name_ar": "بخارة أحمر", "name_en": "Red Plum", "description": "بخارة حمراء طازجة، لون أحمر جذاب وحلاوة عالية.", "features": "عصيرية، مثالية للحلويات والسلطات، محصول محلي طازج وممتاز", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1YbFe5x6NF9noWctOIWycbrvFp0Y2La1w" },
  { "id": 140, "category": "الفواكه", "name_ar": "تفاح أصفر", "name_en": "Yellow Apple", "description": "تفاح أصفر طازج، حلاوة عالية ونكهة عطرية، قشرة رقيقة.", "features": "قوام مقرمش، طعم حلو مميز، مثالي للأكل اليومي للأطفال والكبار", "origin": "مستورد", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "1J5ItraewJdTU3xcXxX4mCIdVWSkGIvG2" },
  { "id": 141, "category": "الفواكه", "name_ar": "مشمش محلي", "name_en": "Local Apricot", "description": "مشمش وطني طازج برتقالي، ناعم وحلو وعطري.", "features": "محصول محلي موسمي، نكهة رائعة، مثالي للأكل الطازج وصنع المربى", "origin": "إنتاج وطني (محلي)", "price": 16.0, "price_unit": "ريال للكيلو", "image_url": "1CGgX2lFlw7jwg7aYdQEWJteaMB8kkhg9" },
  { "id": 142, "category": "الفواكه", "name_ar": "تين شوكي", "name_en": "Prickly Pear", "description": "تين شوكي بقشرة شوكية ولب أحمر حلو عصيري.", "features": "منعش جداً، غني بالألياف، محصول محلي صيفي مميز، يروي العطش", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1ppvJSCLBpeRplUQakzJUrAKltZepT6Kc" },
  { "id": 143, "category": "الفواكه", "name_ar": "قشطة", "name_en": "Custard Apple", "description": "قشطة بقشرة خضراء مزركشة ولب كريمي حلو جداً.", "features": "نكهة الكاسترد، غنية بالسكريات الطبيعية، قوام زبدي فريد ومميز", "origin": "مستورد", "price": 11.0, "price_unit": "ريال للكيلو", "image_url": "1LLkHgW9s0NtdBEMCWl72I6nTyL5DJi_L" },
  { "id": 144, "category": "الفواكه", "name_ar": "تين محلي", "name_en": "Local Fig", "description": "تين وطني طازج بنفسجي غامق، ناعم وحلو جداً.", "features": "غني بالألياف، نكهة غنية، للأكل الطازج أو مع الجبن، موسمي فاخر", "origin": "إنتاج وطني (محلي)", "price": 23.0, "price_unit": "ريال للكيلو", "image_url": "1hnS84xcj25VgfeI1_lg9Y4YqDVNvGbrG" },
  { "id": 145, "category": "الفواكه", "name_ar": "جريب فروت محلي", "name_en": "Local Grapefruit", "description": "جريب فروت وطني أصفر، نكهة حامضة مرة منعشة.", "features": "غني بفيتامين C، مثالي للإفطار الصحي والعصائر، محصول محلي طازج", "origin": "إنتاج وطني (محلي)", "price": 6.5, "price_unit": "ريال للكيلو", "image_url": "1wzJFm5uS33JYSTRbFTh2pGo8xxs6_Hxn" },
  { "id": 146, "category": "الفواكه", "name_ar": "عنب أسود محلي", "name_en": "Local Black Grapes", "description": "عنب أسود وطني، حبات كبيرة حلوة جداً وقليلة البذور.", "features": "حلاوة عالية، محصول محلي فاخر، مثالي كوجبة خفيفة مغذية وصحية", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1QRpEz4DDcJg_kbx3oT7SIFxqcZ6owy2C" },
  { "id": 147, "category": "الفواكه", "name_ar": "عنب أحمر محلي", "name_en": "Local Red Grapes", "description": "عنب أحمر وطني، حبات مقرمشة وحلوة خالية من البذور.", "features": "منعش، مثالي للسلطات والعصائر، حلاوة متوازنة، محصول طازج يومياً", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1RABDV4dyCLaKyamfrgx0-42JyIhIDZlQ" },
  { "id": 148, "category": "الفواكه", "name_ar": "عنب أبيض محلي", "name_en": "Local White Grapes", "description": "عنب أبيض وطني ذهبي، حلاوة ونكهة منعشة.", "features": "مقرمش، محصول محلي طازج وممتاز، مثالي للأكل الطازج والمناسبات", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1Igl9t0o1SFi3cPn6ZFX1L0l0RE35ZHes" },
  { "id": 149, "category": "الفواكه", "name_ar": "جوافة", "name_en": "Guava", "description": "جوافة طازجة خضراء مصفرة، نكهة عطرية مميزة.", "features": "غنية جداً بفيتامين C، تؤكل بقشرتها، مثالية للعصير الطبيعي المنعش", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "1Tr38POXHZLt6q6tffDlm6XB4Qk7jFdDO" },
  { "id": 150, "category": "الفواكه", "name_ar": "كاكا", "name_en": "Persimmon", "description": "كاكا برتقالية زاهية، حلاوة عالية وقوام ناعم.", "features": "غنية بفيتامين A، نكهة حلوة مميزة، تؤكل طازجة أو تجفف بجودة عالية", "origin": "مستورد", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "1hSmSebYQdcpIUUET60Nu_Srw7YcY97rh" },
  { "id": 151, "category": "الفواكه", "name_ar": "أفندي", "name_en": "Mandarin", "description": "أفندي (يوسفي) برتقالي، سهل التقشير وقليل البذور.", "features": "حلو المذاق، محبوب من الأطفال، غني بفيتامين C، للوجبات الخفيفة", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "1rA3eaGFMJhH51hJDTh6hYQIiN9qXUHEF" },
  { "id": 152, "category": "الفواكه", "name_ar": "بابايا محلي", "name_en": "Local Papaya", "description": "بابايا وطنية كبيرة، لب برتقالي حلو ومنعش.", "features": "غنية بإنزيم البابين للهضم، طعم استوائي محلي ممتاز وعالي الجودة", "origin": "إنتاج وطني (محلي)", "price": 8.0, "price_unit": "ريال للكيلو", "image_url": "1wbEtIc_9PYxXwJEnBsTrEjSULAHIoV3h" },
  { "id": 153, "category": "الفواكه", "name_ar": "خوخ محلي", "name_en": "Local Peach", "description": "خوخ وطني أصفر محمر، حلاوة وعصارة ممتازة.", "features": "محصول محلي موسمي، طعم أصيل، مثالي للأكل اليومي، فاكهة فاخرة", "origin": "إنتاج وطني (محلي)", "price": 13.0, "price_unit": "ريال للكيلو", "image_url": "1GPd8fj-g82l_RaXZSzVBZdoJ14UgXqZ7" },
  { "id": 154, "category": "الفواكه", "name_ar": "أناناس بيبي", "name_en": "Baby Pineapple", "description": "أناناس بيبي صغير، حلاوة مركزة ونكهة قوية.", "features": "سهل التقطيع، مثالي لفرد واحد، طعم استوائي فاخر وفريد، حجم مثالي", "origin": "مستورد", "price": 25.0, "price_unit": "ريال للكيلو", "image_url": "1LTyXqi-byuyvwkVs9gnObzfzsfxC2q46" },
  { "id": 155, "category": "الفواكه", "name_ar": "بطيخ طويل محلي", "name_en": "Long Watermelon", "description": "بطيخ طويل وطني، حلاوة عالية ولحم أحمر عصيري.", "features": "حجم عائلي كبير، حلو ومنعش، مثالي للجمعات العائلية في الصيف", "origin": "إنتاج وطني (محلي)", "price": 3.5, "price_unit": "ريال للكيلو", "image_url": "1a-9tiSsdhZ7qlTiQuZM7TsPH7U_ZK6_y" },
  { "id": 156, "category": "الفواكه", "name_ar": "ليم أخضر", "name_en": "Green Lime", "description": "ليم أخضر (لايم) حامض جداً برائحة عطرية قوية.", "features": "منعش، للكوكتيلات والطبخ الآسيوي، نكهة مركزة، جودة توريد عالية", "origin": "مستورد", "price": 10.0, "price_unit": "ريال للكيلو", "image_url": "1cTi41bByxZbHVG2EhqfvK1xie44wr33-" },
  { "id": 157, "category": "الورقيات والأعشاب", "name_ar": "كزبرة", "name_en": "Coriander", "description": "كزبرة طازجة خضراء، أوراق ناعمة ورائحة عطرية قوية.", "features": "غنية بالفيتامينات، لا غنى عنها في المطبخ، تزرع محلياً لنضارة يومية", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "110FJS9mumXqsNOF8gMlapqVrWBc9SGQo" },
  { "id": 158, "category": "الورقيات والأعشاب", "name_ar": "بقدونس محلي", "name_en": "Parsley Local", "description": "بقدونس وطني طازج، أوراق خضراء داكنة ومقرمشة.", "features": "غني بالحديد، نكهة منعشة، للتبولة والسلطات والطبخ، قطف يومي", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1ln2y6DPUQAMYK4pKcruSa88fnINtDBuj" },
  { "id": 159, "category": "الورقيات والأعشاب", "name_ar": "جرجير", "name_en": "Rocket Local", "description": "جرجير محلي طازج، نكهة حادة مميزة ومنعشة.", "features": "غني بمضادات الأكسدة، مثالي مع السلطات والبيتزا، محصول يومي طازج", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1HBEQwVILr-JfScvm3CfNPRO8TK9CcDiI" },
  { "id": 160, "category": "الورقيات والأعشاب", "name_ar": "نعناع", "name_en": "Mint", "description": "نعناع أخضر طازج، أوراق عطرية منعشة جداً.", "features": "مهدئ طبيعي، مثالي للشاي واللبن، رائحة فواحة تضفي انتعاشاً فورياً", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1mXwwtWsn4-lK-TBPfvd4MtO2JqkzaCLx" },
  { "id": 161, "category": "الورقيات والأعشاب", "name_ar": "ملوخية", "name_en": "Molokhia", "description": "ملوخية خضراء طازجة، أوراق ناعمة وعالية الجودة.", "features": "غنية بالفيتامينات، قوام ممتاز بعد الطهي، قطف يومي لضمان الطعم", "origin": "إنتاج وطني (محلي)", "price": 6.0, "price_unit": "ريال للكيلو", "image_url": "1iSHN2ESMDyCjAMaGLU8GP_exrsDNJdDx" },
  { "id": 162, "category": "الورقيات والأعشاب", "name_ar": "خس مدور محلي", "name_en": "Round Lettuce Local", "description": "خس مدور وطني، رأس متماسك وأوراق مقرمشة.", "features": "غني بالماء، قرمشة عالية، مثالي للسلطات والسندويشات، محصول طازج", "origin": "إنتاج وطني (محلي)", "price": 9.0, "price_unit": "ريال للكيلو", "image_url": "18rBQ9sD4Zswl3-GFu15s9s8fpa7EKD9R" },
  { "id": 163, "category": "الورقيات والأعشاب", "name_ar": "سبانخ محلي", "name_en": "Local Spinach", "description": "سبانخ محلي طازج، أوراق خضراء داكنة غنية.", "features": "غنية بالحديد والفيتامينات، تطهى بسرعة، نكهة مميزة للأطباق الصحية", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1E3IJJJvG0zDPjjQ3SA1P4TzR20qMPbgx" },
  { "id": 164, "category": "الورقيات والأعشاب", "name_ar": "شبت", "name_en": "Dill", "description": "شبت طازج، أوراق خضراء ريشية ونكهة مميزة.", "features": "رائحة عطرية، مثالي مع السمك والمخللات، يضاف في آخر مراحل الطهي", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1J-zKC7Tbs2nQJeFxwWnFFJG2rQu32dDV" },
  { "id": 165, "category": "الورقيات والأعشاب", "name_ar": "كراث محلي", "name_en": "Local Leek", "description": "كراث محلي أخضر طازج، نكهة معتدلة ولذيذة.", "features": "يستخدم في الشوربات والطبخ، محصول يومي طازج، يضفي نكهة عميقة", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1AUaWuJrVzvm0Ix4TUG-qEcVVVKEHHWzp" },
  { "id": 166, "category": "الورقيات والأعشاب", "name_ar": "خس طويل محلي", "name_en": "Romaine Lettuce Local", "description": "خس رومين طويل وطني، أوراق مقرمشة طويلة.", "features": "غني بالماء، قرمشة عالية، مثالي لسلطة السيزر والسندويشات الكبرى", "origin": "إنتاج وطني (محلي)", "price": 7.0, "price_unit": "ريال للكيلو", "image_url": "1PxkUdLlpeuKqlSnGt2axdPoQvUtJ0ZOw" },
  { "id": 167, "category": "الورقيات والأعشاب", "name_ar": "رجلة", "name_en": "Purslane", "description": "رجلة (بقلة) طازجة، أوراق خضراء صغيرة سميكة.", "features": "نكهة حامضة قليلاً، غنية جداً بالأوميغا 3، فوائد صحية كبيرة ومنعشة", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1OtilTGLsBH37KhA_eg046p3O-D_NHPkS" },
  { "id": 168, "category": "الورقيات والأعشاب", "name_ar": "فجل أحمر", "name_en": "Red Radish", "description": "فجل أحمر طازج، حار ومنعش وقوي النكهة.", "features": "يفتح الشهية، مقرمش، يضاف للسلطات والمقبلات الشعبية، محصول طازج", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1XKo8yO71NIBMGEUWxWM2N-ABeFa9o95j" },
  { "id": 169, "category": "الورقيات والأعشاب", "name_ar": "فجل أبيض", "name_en": "White Radish", "description": "فجل أبيض طويل، نكهة حارة قوية ومنعشة.", "features": "مقرمش، مثالي للأطباق الآسيوية والسلطات والمخللات، نضارة مضمونة", "origin": "إنتاج وطني (محلي)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1vXKhI0PKDNiQfgw6Y98djIQGDI_HNMTS" },
  { "id": 170, "category": "الورقيات والأعشاب", "name_ar": "كرفس محلي", "name_en": "Local Celery", "description": "كرفس وطني طازج، سيقان مقرمشة ونكهة مميزة.", "features": "غني بالألياف، مثالي للعصائر الصحية والسلطات، جودة محلية عالية", "origin": "إنتاج وطني (محلي)", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "1Yf_lj5bv4M2KUa3Zw220TLLtSKaUN5zW" },
  { "id": 171, "category": "الورقيات والأعشاب", "name_ar": "براعم ألفالفا", "name_en": "Alfalfa Sprouts", "description": "براعم ألفالفا طازجة وخفيفة، نكهة ناعمة ومنعشة.", "features": "غنية بالأنزيمات، تزيد القيمة الغذائية للسندويشات والسلطات الراقية", "origin": "مستورد", "price": 11.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "158_8pwt5GB_qeqs0e0lKXWZufp5ryykZ" },
  { "id": 172, "category": "الورقيات والأعشاب", "name_ar": "أوراق خيزران", "name_en": "Bamboo Leaves", "description": "أوراق خيزران طازجة خضراء، للتغليف والطهي.", "features": "تضفي نكهة مميزة جداً عند الطهي بالبخار في المطبخ الآسيوي الفاخر", "origin": "مستورد", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "10dc-r6PQODq13No8JtF2skFkHbwJ84ph" },
  { "id": 173, "category": "الورقيات والأعشاب", "name_ar": "أوراق موز", "name_en": "Banana Leaves", "description": "أوراق موز كبيرة طازجة، تستخدم لتغليف الطعام.", "features": "تضفي رائحة ونكهة خفيفة ومميزة عند الشوي أو الطهي بالبخار", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1djiSu9GqC9RX_lQiAZjFW-q8TBecHq-z" },
  { "id": 174, "category": "الورقيات والأعشاب", "name_ar": "ريحان مستورد", "name_en": "Imported Basil", "description": "ريحان طازج عطر، نكهة حلوة قوية ومميزة جداً.", "features": "أساسي في المطبخ الإيطالي، مثالي للبيستو والسلطات الفاخرة، عطر فواح", "origin": "مستورد", "price": 58.0, "price_unit": "ريال للكيلو", "image_url": "1FTG1jfODpR7EDQ9JMUrBsTV2CqkNVIrV" },
  { "id": 175, "category": "الورقيات والأعشاب", "name_ar": "شيكوري أحمر", "name_en": "Red Chicory", "description": "شيكوري أحمر (راديكيو) بنكهة مرة مميزة ومنعشة.", "features": "يضيف لوناً ونكهة للسلطات، مثالي للشوي، جودة توريد ممتازة وعالية", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "1uGMHuSn22VUiAV622LIBq-OEQNqSqE4u" },
  { "id": 176, "category": "الورقيات والأعشاب", "name_ar": "شيكوري أصفر", "name_en": "Yellow Chicory", "description": "شيكوري أصفر، نكهة مرة خفيفة وقوام مقرمش.", "features": "مثالي للسلطات الفاخرة، يضيف رقياً وتنوعاً للأطباق العالمية الراقية", "origin": "مستورد", "price": 38.0, "price_unit": "ريال للكيلو", "image_url": "1CSZqFq-sX0rYbPyuu8W8WJOGFW4Htq6v" },
  { "id": 177, "category": "الورقيات والأعشاب", "name_ar": "ثوم معمر", "name_en": "Chives", "description": "ثوم معمر طازج، أعواد خضراء بنكهة بصل خفيفة.", "features": "يستخدم للتزيين وإضافة نكهة راقية للسلطات والبطاطس والشوربات", "origin": "مستورد", "price": 70.0, "price_unit": "ريال للكيلو", "image_url": "1lJZH73CGNWzz1nfHcL-IkpCxsA26_pJb" },
  { "id": 178, "category": "الورقيات والأعشاب", "name_ar": "إنديف مستورد", "name_en": "Imported Endive", "description": "إنديف بلجيكي أبيض مصفر، أوراق متماسكة مقرمشة.", "features": "نكهة مرة خفيفة، مثالي لتقديم المقبلات الراقية بأسلوب مبتكر", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1NdOga_IQhq8Yr0X8kzhcUTzlG-Kni75N" },
  { "id": 179, "category": "الورقيات والأعشاب", "name_ar": "إنديف أصفر", "name_en": "Yellow Endive", "description": "إنديف أصفر بنفس الخصائص السابقة بلون أفتح.", "features": "نكهة فريدة، يضفي جمالية عالية للسلطات والمقبلات العالمية الراقية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1POvZCC7LMPswpRUhrx2z6Zma2Iu-QUir" },
  { "id": 180, "category": "الورقيات والأعشاب", "name_ar": "ريحان تاي أرجواني", "name_en": "Purple Thai Basil", "description": "ريحان تايلي أرجواني بنكهة حارة تشبه اليانسون.", "features": "أساسي في المطبخ التايلاندي، يتحمل درجات الحرارة العالية في الطهي", "origin": "مستورد", "price": 68.0, "price_unit": "ريال للكيلو", "image_url": "1h4MMHnCDUPOVTWzzo-YqQmwt5_e8_hjK" },
  { "id": 181, "category": "الورقيات والأعشاب", "name_ar": "روزماري مستورد", "name_en": "Imported Rosemary", "description": "روزماري طازج، أوراق إبرية عطرية ونكهة قوية.", "features": "مثالي لتتبيل اللحوم والدجاج والمخبوزات، رائحة عطرية فواحة جداً", "origin": "مستورد", "price": 58.0, "price_unit": "ريال للكيلو", "image_url": "13QR_PVksyzM8yBqvRDYCUYRIWNp_U5hI" },
  { "id": 182, "category": "الورقيات والأعشاب", "name_ar": "أعشاب الميرمية", "name_en": "Sage Herbs", "description": "مريمية طازجة بنكهة ترابية مميزة وعميقة.", "features": "تستخدم مع الدجاج واللحوم والوصفات الإيطالية، فوائد صحية معروفة", "origin": "مستورد", "price": 65.0, "price_unit": "ريال للكيلو", "image_url": "1FH910F5Y1jO90bwY9U8Kk3xYvdz1t5XX" },
  { "id": 183, "category": "الورقيات والأعشاب", "name_ar": "أعشاب الطرخون", "name_en": "Tarragon Herbs", "description": "طرخون طازج بنكهة تشبه اليانسون ناعمة وراقية.", "features": "مثالي للصلصات الكريمية، الدجاج، والسلطات العالمية الراقية والفاخرة", "origin": "مستورد", "price": 88.0, "price_unit": "ريال للكيلو", "image_url": "1VbNMHBD_-Qr3rDdb__GEndyqs7_lUfTo" },
  { "id": 184, "category": "الورقيات والأعشاب", "name_ar": "كيل هولندا", "name_en": "Kale (Holland)", "description": "كيل هولندي طازج، أوراق خضراء داكنة مجعدة.", "features": "سوبر فود، غني بالعناصر الغذائية، للسلطات والعصائر ورقائق الكيل", "origin": "هولندا", "price": 32.0, "price_unit": "ريال للكيلو", "image_url": "1pwvZnBpa5HCKra8eFpvFSAdenySs9eVC" },
  { "id": 185, "category": "الورقيات والأعشاب", "name_ar": "كراث (Leeks)", "name_en": "Leeks (Imported)", "description": "كراث مستورد بنكهة بصل معتدلة وراقية.", "features": "سيقان طويلة بيضاء وخضراء، مثالي للشوربات واليخنات والطبخ البطيء", "origin": "مستورد", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "17zjSTHrYcxWdEFUxXql7e5I4pNOpAidF" },
  { "id": 186, "category": "الورقيات والأعشاب", "name_ar": "ليمون غراس", "name_en": "Lemon Grass", "description": "عشبة الليمون العطرية بنكهة ليمون منعشة جداً.", "features": "أساسي في المطبخ التايلاندي، يستخدم للشاي والطهي والصلصات الاستوائية", "origin": "مستورد", "price": 33.0, "price_unit": "ريال للكيلو", "image_url": "1I8hGrc6pXr0lIpATCQh3ETsrT8wrhq_Z" },
  { "id": 187, "category": "الورقيات والأعشاب", "name_ar": "ورق ليمون", "name_en": "Lemon Leaves", "description": "أوراق الليمون الطازجة، عطرية وفواحة جداً.", "features": "تستخدم لتغليف الطعام، إضافة نكهة للشاي، أو في الطبخ العطري", "origin": "مستورد", "price": 43.0, "price_unit": "ريال للكيلو", "image_url": "1sqImWM_wfw8X9imsuCRN0r7M8qPgnW9B" },
  { "id": 188, "category": "الورقيات والأعشاب", "name_ar": "خس بوسطن", "name_en": "Boston Lettuce", "description": "خس بوسطن برأس ناعم وأوراق زبدية طرية.", "features": "نكهة خفيفة، مثالي للسلطات العالمية الفاخرة وتزيين الأطباق الراقية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1MX2T4kprPqm8P0pXayFe7SXKJdyaebr8" },
  { "id": 189, "category": "الورقيات والأعشاب", "name_ar": "خس فريس أخضر", "name_en": "Green Frisee Lettuce", "description": "خس فريس أخضر مجعد، نكهة مرة خفيفة ومنعشة.", "features": "يضيف قرمشة وشكلاً رائعاً للسلطات، جودة توريد عالية للمطاعم الكبرى", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1jDfgR4PuzHAnckWmNI3F7IUufkF13li8" },
  { "id": 190, "category": "الورقيات والأعشاب", "name_ar": "خس فريس أصفر", "name_en": "Yellow Frisee Lettuce", "description": "خس فريس أصفر مشابه للنوع السابق بلون ذهبي فاتح.", "features": "مثالي للسلطات المختلطة، يضيف تنوعاً بصرياً ونكهة مميزة للأطباق", "origin": "مستورد", "price": 48.0, "price_unit": "ريال للكيلو", "image_url": "1wCOmkMDRJBz_WaF0ycwcOWRz92dRb5jM" },
  { "id": 191, "category": "الورقيات والأعشاب", "name_ar": "خس راديكيو", "name_en": "Radicchio Lettuce", "description": "راديكيو أحمر برأس صلب ونكهة مرة مميزة.", "features": "أوراق حمراء بعروق بيضاء، مثالي للشوي والسلطات العالمية المبتكرة", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1XM7QdI-I5AIPOi5qJg1WYjrNMNsovUfA" },
  { "id": 192, "category": "الورقيات والأعشاب", "name_ar": "خس بيبي جيم", "name_en": "Baby Gem Lettuce", "description": "خس بيبي جيم صغير الحجم ومقرمش جداً وحلو.", "features": "حجم مثالي لفرد واحد، أساسي لسلطة السيزر الفاخرة، قرمشة عالية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1SLVu7B75FeXRDXaK0N0FE-LBfP6-Zdnl" },
  { "id": 193, "category": "الورقيات والأعشاب", "name_ar": "بوك تشوي", "name_en": "Bok Choy", "description": "بوك تشوي (كرنب صيني) طازج بنكهة خفيفة ومنعشة.", "features": "سيقان بيضاء وأوراق خضراء، أساسي في الطبخ الآسيوي، يطهى سريعاً", "origin": "مستورد", "price": 23.0, "price_unit": "ريال للكيلو", "image_url": "1v3y8lB277FWQtAXqlXx43gbQIOcVl3dn" },
  { "id": 194, "category": "الورقيات والأعشاب", "name_ar": "خس لولو بيوندي", "name_en": "Lollo Bionda Lettuce", "description": "خس لولو بيوندي بأوراق مجعدة خضراء فاتحة.", "features": "مقرمش ومنعش، يضيف شكلاً جمالياً وحجماً للسلطات، محصول طازج فاخر", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1O6uyCAFY5Jh9c-9J-MnGiD85IxLQv8zE" },
  { "id": 195, "category": "الورقيات والأعشاب", "name_ar": "خس لولو روسو", "name_en": "Lollo Rosso Lettuce", "description": "خس لولو روسو بأوراق مجعدة حمراء الأطراف.", "features": "نكهة خفيفة، مثالي لإضفاء اللون للسلطات وتزيين أطباق التقديم الراقية", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1cSmCIP0fUfhAd5qW_mGo_6t_wJpub16v" },
  { "id": 196, "category": "الورقيات والأعشاب", "name_ar": "خس أوراق البلوط", "name_en": "Oak Leaf Lettuce", "description": "خس بأوراق تشبه أوراق البلوط، نكهة حلوة معتدلة.", "features": "ناعم ولذيذ، يتوفر باللونين الأخضر والأحمر، يضيف تنوعاً للسلطات", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "1tqmnOuotNzTt6I9if3--gIlLIo9_X9Z4" },
  { "id": 197, "category": "الورقيات والأعشاب", "name_ar": "جرجير بيبي", "name_en": "Baby Rocket", "description": "جرجير بيبي صغير الأوراق، نكهة ناعمة وحادة بشكل متوازن.", "features": "مثالي للسلطات العالمية الراقية، جودة توريد متميزة للمطاعم الكبرى", "origin": "مستورد", "price": 65.0, "price_unit": "ريال للكيلو", "image_url": "1yedV0D2aBzZnktt963ykh85NBA50mIGf" },
  { "id": 198, "category": "الورقيات والأعشاب", "name_ar": "خس رومان", "name_en": "Romaine Lettuce", "description": "خس رومين مستورد، طويل ومقرمش جداً.", "features": "جودة عالية، مثالي لسلطة السيزر والجمعات، قوام متماسك ومنعش", "origin": "مستورد", "price": 35.0, "price_unit": "ريال للكيلو", "image_url": "15Er7Yg0eXfsyFHlM5komcGxHgsZPednq" },
  { "id": 199, "category": "الورقيات والأعشاب", "name_ar": "ورق لايم كافير", "name_en": "Kaffir Lime Leaves", "description": "أوراق لايم كافير عطرية جداً، نكهة ليمون قوية.", "features": "أساسية في المطبخ التايلاندي، تضفي نكهة ليمون عميقة وعطرية فواحة", "origin": "مستورد", "price": 48.0, "price_unit": "ريال للكيلو", "image_url": "1fYSZAT7-Ij-97PWrBa7XjeJdcmrD-ITN" },
  { "id": 200, "category": "الورقيات والأعشاب", "name_ar": "أعشاب مايكرو", "name_en": "Micro Herbs", "description": "مجموعة أعشاب مايكرو صغيرة بنكهة مركزة.", "features": "مثالية لتزيين الأطباق الفاخرة، جودة فندقية، نكهات متنوعة وقوية", "origin": "مستورد", "price": 75.0, "price_unit": "ريال للكيلو", "image_url": "17l0F40UMG6S6KoeykDXaxO1Kc5fP1lNh" },
  { "id": 201, "category": "الورقيات والأعشاب", "name_ar": "أوريغانو طازج", "name_en": "Fresh Oregano", "description": "أوريغانو طازج، أوراق خضراء صغيرة ونكهة قوية.", "features": "مثالي للبيتزا والصلصات الإيطالية، رائحة عطرية فواحة عند الطهي", "origin": "مستورد", "price": 68.0, "price_unit": "ريال للكيلو", "image_url": "11y0RV71DVsW9CiximQkFICi7oBh2nTCl" },
  { "id": 202, "category": "الورقيات والأعشاب", "name_ar": "بقدونس فرنسي", "name_en": "French Parsley", "description": "بقدونس فرنسي مسطح الأوراق، نكهة أقوى من العادي.", "features": "مثالي للطبخ الفرنسي، نكهة مركزة وعطرية، يستخدم في تتبيل اللحوم", "origin": "مستورد", "price": 28.0, "price_unit": "ريال للكيلو", "image_url": "1RDSCGCLKc2k7xcFhB1WvDXRP0Yj0WKIM" },
  { "id": 203, "category": "الورقيات والأعشاب", "name_ar": "بقدونس مجعد", "name_en": "Curly Parsley", "description": "بقدونس مجعد الأوراق، يستخدم غالباً للتزيين.", "features": "يحتفظ بمظهره الجذاب لفترة طويلة، يضيف لمسة جمالية رائعة للأطباق", "origin": "مستورد", "price": 29.0, "price_unit": "ريال للكيلو", "image_url": "1ZpAlmH9Jz2lAzfUK4AP8wJ-4CgKFWHVS" },
  { "id": 204, "category": "الورقيات والأعشاب", "name_ar": "ساكورا ميكس كريس", "name_en": "Sakura Mix Cress", "description": "ميكس من الكريس (الجرجير الصغير) بنكهات مختلفة.", "features": "مثالي للسلطات العالمية الفاخرة، نكهات مركزة ومتنوعة، شكل جذاب", "origin": "مستورد", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "1OWUrKvB0egcWQbdYD5x3vy9cTEaBYcI_" },
  { "id": 205, "category": "الورقيات والأعشاب", "name_ar": "شيسو ميكس", "name_en": "Shiso Mix", "description": "ميكس من أوراق الشيسو اليابانية الفاخرة.", "features": "نكهة فريدة ومنعشة، مثالي للمطبخ الياباني (السوشي والساشيمي) الراقي", "origin": "مستورد", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "1DMSxjUNFmT1CtD5kX7qvHw8ELqfKJopY" },
  { "id": 206, "category": "الورقيات والأعشاب", "name_ar": "براعم ساكورا ميكس", "name_en": "Sakura Mix Sprouts", "description": "براعم صغيرة من ميكس ساكورا، نكهة مركزة.", "features": "تضيف رقياً وقيمة غذائية للسندويشات والسلطات والمقبلات العالمية", "origin": "مستورد", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "1RxUTcctn3gRPYv1Aluk8EIqhkQqQkQaq" },
  { "id": 207, "category": "الورقيات والأعشاب", "name_ar": "أوراق الزعتر", "name_en": "Thyme Leaves", "description": "زعتر طازج، أوراق صغيرة عطرية جداً.", "features": "مثالي لتتبيل اللحوم والدجاج والخضروات، رائحة عطرية تدوم طويلاً", "origin": "مستورد", "price": 58.0, "price_unit": "ريال للكيلو", "image_url": "1XN2IXj6HtHeTkAHA1ffwYkbbsqDM1u0c" },
  { "id": 208, "category": "الورقيات والأعشاب", "name_ar": "زعتر بري طازج", "name_en": "Fresh Wild Thyme", "description": "زعتر بري طازج بنكهة أقوى من العادي.", "features": "رائحة فواحة جداً، مثالي للأطباق التقليدية والعالمية، جودة استثنائية", "origin": "مستورد", "price": 58.0, "price_unit": "ريال للكيلو", "image_url": "1YoCylBcgP08EZj4stR1eVDT_tywadEPt" },
  { "id": 209, "category": "الورقيات والأعشاب", "name_ar": "راوند مستورد", "name_en": "Imported Rhubarb", "description": "راوند (ريباس) بساق حمراء وخضراء حامضة.", "features": "نكهة حامضة جداً ومميزة، يستخدم في الحلويات الفاخرة والمربيات", "origin": "مستورد", "price": 26.0, "price_unit": "ريال للكيلو", "image_url": "1e87sMikDk1o3DGyTVCTlY64RNLrow1zx" },
  { "id": 210, "category": "الورقيات والأعشاب", "name_ar": "كرفس طازج (USA)", "name_en": "Fresh Celery (USA)", "description": "كرفس أمريكي طازج، سيقان طويلة مقرمشة.", "features": "جودة تصدير ممتازة، نكهة قوية، مثالي للعصائر الصحية والوجبات الخفيفة", "origin": "الولايات المتحدة الأمريكية", "price": 18.0, "price_unit": "ريال للكيلو", "image_url": "1W0FSNRlm_HRrLDsOsDePjSEJSm0efj6Q" },
  { "id": 211, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "يقطين القصيم", "name_en": "Qassim Pumpkin", "description": "يقطين القصيم الشهير، لون برتقالي وحلاوة عالية.", "features": "جودة فائقة، مثالي للحلويات والحساء، منتج محلي عريق من منطقة القصيم", "origin": "إنتاج وطني (القصيم)", "price": 5.5, "price_unit": "ريال للكيلو", "image_url": "19JOwuFcqrQj7XLi-QtP5ib9l30ehaEOG" },
  { "id": 212, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فلفل شقراء حار", "name_en": "Shaqra Chili", "description": "فلفل حار من شقراء، حرارة قوية ونكهة مميزة.", "features": "محصول محلي ممتاز، مثالي لإضافة نكهة حارة أصيلة للأطباق العربية", "origin": "إنتاج وطني (شقراء)", "price": 12.0, "price_unit": "ريال للكيلو", "image_url": "1TIsiwKUtDJu3YTlhNxty2NQ9Aa4_P0Up" },
  { "id": 213, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "بصل القصيم", "name_en": "Qassim Onion", "description": "بصل أحمر وطني، نكهة قوية وقدرة تخزين.", "features": "جودة عالية، من أشهر أنواع البصل في المملكة، نكهة مركزة وممتازة", "origin": "إنتاج وطني (القصيم)", "price": 4.0, "price_unit": "ريال للكيلو", "image_url": "17Wcmou9mLbX38KGMVpSULFDR8V6j5j2L" },
  { "id": 214, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "قرع أخضر طويل", "name_en": "Long Green Squash", "description": "قرع أخضر طويل (كوسا صيفي) نكهة خفيفة.", "features": "محصول طازج، مثالي للسلق والشوي واليخنات، قوام متماسك ولذيذ", "origin": "إنتاج وطني (محلي)", "price": 5.5, "price_unit": "ريال للكيلو", "image_url": "1sJ7QxNrTtpPUPMgVZe7NzmYKH-o8RXxb" },
  { "id": 215, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "بصل أخضر القصيم", "name_en": "Qassim Spring Onion", "description": "بصل أخضر طازج، جزء أبيض لذيذ وأوراق خضراء.", "features": "نكهة معتدلة، مثالي للسلطات والتزيين، محصول طازج من مزارع القصيم", "origin": "إنتاج وطني (القصيم)", "price": 4.5, "price_unit": "ريال للكيلو", "image_url": "1AH9RxV6TY_oOey3FPylKbqWJvisjkIcw" },
  { "id": 216, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "كراث القصيم", "name_en": "Qassim Leek", "description": "كراث وطني طازج بنكهة مميزة.", "features": "محصول يومي، مثالي للشوربات والطبخ الشعبي، نكهة مركزة وطازجة", "origin": "إنتاج وطني (القصيم)", "price": 1.5, "price_unit": "ريال (للقطعة - PC)", "image_url": "1PRhIa8dg5aaXwEuJhX8SBE-w9835XHzi" },
  { "id": 217, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "سكري مفتل", "name_en": "Sukari Muftal", "description": "تمر سكري مفتل فاخر، حبات ذهبية نصف جافة.", "features": "منتج فاخر للضيافة، حلاوة طبيعية عالية، عبوة 3 كغم، جودة قصيمية أصيلة", "origin": "إنتاج وطني (القصيم)", "price": 120.0, "price_unit": "ريال (للعبوة 3 كغم)", "image_url": "1qBpgXaYK9QEYqsNzJYFDhqev6ji1RLKR" },
  { "id": 218, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "مجدول القصيم", "name_en": "Qassim Majdool", "description": "تمر مجدول فاخر، حبات كبيرة طرية.", "features": "طعم كراميل لا يقاوم، من أرقى أنواع التمر، مثالي للهدايا والمناسبات", "origin": "إنتاج وطني (القصيم)", "price": 60.0, "price_unit": "ريال للكيلو", "image_url": "1cqmFCizZGhXcGGPyG6DTYc1g5zCXvn3s" },
  { "id": 219, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "صقعي القصيم", "name_en": "Qassim Sagai", "description": "تمر صقعي بلون أحمر ذهبي وحلاوة متوازنة.", "features": "قوام متماسك، مثالي للتخزين الطويل، يحتفظ بجودته ونكهته المميزة", "origin": "إنتاج وطني (القصيم)", "price": 55.0, "price_unit": "ريال للكيلو", "image_url": "17EiWZaTE2KpuxduetrhRFuRP-3E-a2ld" },
  { "id": 220, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "مبروم المدينة", "name_en": "Madinah Mabroom", "description": "تمر مبروم المدينة، حبات طويلة وطنية ناعمة.", "features": "نكهة غنية بالدبس، من تمور المدينة الفاخرة، قوام طري ومحبب للجميع", "origin": "إنتاج وطني (المدينة المنورة)", "price": 70.0, "price_unit": "ريال للكيلو", "image_url": "1nfmCv36v-z6Biob5R1esAZRYK0g0DyGt" },
  { "id": 221, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "صفاوي المدينة", "name_en": "Madinah Safawi", "description": "تمر صفاوي أسود اللون، متوسط الحجم وطري.", "features": "غني بالعناصر الغذائية، طعم لذيذ ومنعش، مثالي للإفطار اليومي الصحي", "origin": "إنتاج وطني (المدينة المنورة)", "price": 45.0, "price_unit": "ريال للكيلو", "image_url": "1aRcXxAeUK0iP1NRB19HBbYZsW0kJlgAT" },
  { "id": 222, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "عنبر المدينة", "name_en": "Madinah Anbar", "description": "تمر عنبر المدينة، كبير الحجم وأسود داكن.", "features": "من أندر وأغلى التمور، طعم استثنائي وفريد، قوام طري جداً وفاخر", "origin": "إنتاج وطني (المدينة المنورة)", "price": 90.0, "price_unit": "ريال للكيلو", "image_url": "1Vekv_ioZAbMpJvKDePbClsqPh2jmfIUa" },
  { "id": 223, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "عجوة ملكي", "name_en": "Royal Ajwa", "description": "تمر عجوة ملكي فاخر، وطني ناعم ومبارك.", "features": "فوائد صحية عظيمة، تمور نبوية فاخرة، مثالية للهدايا بأعلى المعايير", "origin": "إنتاج وطني (المدينة المنورة)", "price": 80.0, "price_unit": "ريال للكيلو", "image_url": "18-h4PfWk8YFF6BXSIG63ESCCdduJsnsy" },
  { "id": 224, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "رطب سكري", "name_en": "Sukari Rutab", "description": "رطب سكري طازج طري جداً وحلو.", "features": "مرحلة الرطوبة الطازجة، طعم لا يقاوم، محصول موسمي يعبأ بعناية فائقة", "origin": "إنتاج وطني", "price": 45.0, "price_unit": "ريال (للعبوة - Ctn)", "image_url": "1W1qrGiqe2BM2H3ltgrD9_g7NTNasszWA" },
  { "id": 225, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "سلة الفواكه", "name_en": "Fruit Basket (S)", "description": "سلة فواكه مشكلة صغيرة بتنسيق جميل.", "features": "تشكيلة موسمية من أفضل الفواكه الطازجة، مثالية للهدايا والمناسبات", "origin": "تشكيلة متنوعة", "price": 50.0, "price_unit": "ريال (للسلة)", "image_url": "1_j6k8KEPp1Iy880aqBz9inAzk6XXXiK5" },
  { "id": 226, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "صندوق الخضار", "name_en": "Vegetable Box (M)", "description": "صندوق خضار متوسط متنوع ومختار.", "features": "تشكيلة خضروات طازجة مختارة بعناية، مثالي للعائلات، جودة توريد عالية", "origin": "تشكيلة محلية ومستوردة", "price": 75.0, "price_unit": "ريال (للصندوق)", "image_url": "1_JjTPMTV2dQGhfokQHLW8wogwrH6si0D" },
  { "id": 227, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "سلة الورقيات", "name_en": "Leafy Greens Basket L", "description": "سلة كبيرة من الورقيات الطازجة والوطنية المنوعة", "features": "خس، جرجير، نعناع، كزبرة وأكثر، مثالية لعشاق السلطات الصحية يومياً", "origin": "إنتاج وطني (محلي)", "price": 30.0, "price_unit": "ريال (للسلة)", "image_url": "1rQEYprxOY0cQ9sV-NtcTZw9M1rmguG7C" },
  { "id": 228, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "بيض الغربية", "name_en": "Gharbia Eggs Box", "description": "بيض بلدي طازج من الغربية عالي الجودة.", "features": "صفار ذهبي غني، مثالي للطهي، يعبأ في كرتون خاص لضمان السلامة", "origin": "إنتاج وطني (الغربية)", "price": 185.0, "price_unit": "ريال (للعبوة - Box)", "image_url": "1TT1F3HP7d86fI2T9yj8-NTLuxnS5_ZWQ" },
  { "id": 229, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "زهور صالحة للأكل", "name_en": "Edible Flowers", "description": "مجموعة من الزهور الطازجة الصالحة للأكل.", "features": "ألوان زاهية، مثالية لتزيين الحلويات والسلطات الفاخرة، لمسة فنية راقية", "origin": "مستورد", "price": 170.0, "price_unit": "ريال للكيلو", "image_url": "1I87dr24LWhEcFhBNicncaKyiTzxlS0Lk" },
  { "id": 230, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "جوز الهند", "name_en": "Coconut", "description": "جوز هند طازج بقشرة بنية وماء لذيذ.", "features": "يمكن شرب مائه وأكل لحمه الأبيض، مثالي للوصفات الاستوائية المنعشة", "origin": "مستورد", "price": 8.0, "price_unit": "ريال (للقطعة - PC)", "image_url": "1rapet36SXQmu9ACNERS-4COqTmwHemsH" },
  { "id": 231, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "قصب سكر", "name_en": "Sugar Cane", "description": "أعواد قصب سكر طازجة وعصيرية.", "features": "مصدر طبيعي للسكر، يمكن مضغه لاستخراج العصير الحلو المنعش جداً", "origin": "مستورد", "price": 20.0, "price_unit": "ريال للكيلو", "image_url": "1yoTHxJx9TwQvsO68pvd3TP5SfFWnrd_S" },
  { "id": 232, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فطر ترمبيت أسود", "name_en": "Black Trumpet Mushroom", "description": "فطر ترمبيت أسود فاخر ونادر جداً.", "features": "نكهة ترابية قوية، من أفخر أنواع الفطر البري، يتطلب معالجة خاصة", "origin": "مستورد", "price": 0, "price_unit": "يحدد لاحقاً", "image_url": "1f7hxktfW9NNZFLX26cHHVvKBnUp3BGr2" },
  { "id": 233, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فطر بلوفوت", "name_en": "Bluefoot Mushroom", "description": "فطر بلوفوت بقاعدة زرقاء نادرة.", "features": "نكهة جوزية خفيفة، منتج موسمي نادر، مثالي للشوي والصلصات العالمية", "origin": "مستورد", "price": 0, "price_unit": "يحدد لاحقاً", "image_url": "1t1S5zPov-t98iYQgGivFA769cwwfCh7i" },
  { "id": 234, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "فطر جيرول صغير", "name_en": "Small Girolle Mushroom", "description": "فطر جيرول (شانتيريل) أصفر ذهبي.", "features": "نكهة فاكهية مميزة، من أشهر أنواع الفطر البري، مثالي للريزوتو الفاخر", "origin": "مستورد", "price": 0, "price_unit": "يحدد لاحقاً", "image_url": "1r8zDqOWrgDD4Cq1RZSe2sKyHqm26Wkvh" },
  { "id": 235, "category": "أصناف القصيم والتمور ومنوعة", "name_ar": "توت أسود طائفي", "name_en": "Taifi Blackberries", "description": "توت أسود طائفي طازج وحلو جداً.", "features": "إنتاج محلي محدود، طعم استثنائي، من مزارع الطائف العريقة، معالجة خاصة", "origin": "إنتاج وطني (الطائف)", "price": 0, "price_unit": "يحدد لاحقاً", "image_url": "1o8d2SaaS32HpINFb60p2HRbBHxotKvF0" }
];

const generateFullCatalog = (): Product[] => {
  return rawJsonData.map(item => {
    const mainImage = fixDriveLink(item.image_url);
    return {
      id: item.id,
      name_ar: item.name_ar,
      name_en: item.name_en,
      category: mapCategory(item.category, item.name_ar),
      price: item.price,
      image: mainImage,
      gallery: [
        mainImage,
        `https://picsum.photos/seed/${item.id + 100}/800/800`,
        `https://picsum.photos/seed/${item.id + 200}/800/800`
      ],
      unit_ar: item.price_unit,
      unit_en: mapUnitArToEn(item.price_unit),
      description_ar: item.description,
      description_en: item.name_en + " - Institutional Supply Grade.",
      features_ar: item.features,
      origin_ar: item.origin,
      origin_en: item.origin === "مستورد" ? "Imported" : "KSA Local",
      stock_quantity: 1000,
      min_threshold: 50
    };
  });
};

export const mockProducts: Product[] = generateFullCatalog();export const REAL_PRODUCTS: any[] = [];
