[build]
  command = "npm run build"
  publish = "dist" # هذا هو المجلد الذي يحتوي على المتجر الفعلي بعد البناء

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false" # لمنع تعطيل النشر بسبب مفاتيح Firebase

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Content-Type = "application/javascript"
